// Copyright lowRISC contributors (OpenTitan project).
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0

// This file was generated automatically.
// Please do not modify content of this file directly.
// File generated by using template: "toplevel.rs.tpl"
// To regenerate this file follow OpenTitan topgen documentations.

#![allow(dead_code)]

//! This file contains enums and consts for use within the Rust codebase.
//!
//! These definitions are for information that depends on the top-specific chip
//! configuration, which includes:
//! - Device Memory Information (for Peripherals and Memory)
//! - PLIC Interrupt ID Names and Source Mappings
//! - Alert ID Names and Source Mappings
//! - Power Manager Wakeups

use core::convert::TryFrom;

/// Peripheral base address for rv_timer in top peppermint.
///
/// This should be used with #mmio_region_from_addr to access the memory-mapped
/// registers associated with the peripheral (usually via a DIF).
pub const RV_TIMER_BASE_ADDR: usize = 0x40000000;

/// Peripheral size for rv_timer in top peppermint.
///
/// This is the size (in bytes) of the peripheral's reserved memory area. All
/// memory-mapped registers associated with this peripheral should have an
/// address between #RV_TIMER_BASE_ADDR and
/// `RV_TIMER_BASE_ADDR + RV_TIMER_SIZE_BYTES`.
pub const RV_TIMER_SIZE_BYTES: usize = 0x200;

/// Peripheral base address for core device on otp_ctrl in top peppermint.
///
/// This should be used with #mmio_region_from_addr to access the memory-mapped
/// registers associated with the peripheral (usually via a DIF).
pub const OTP_CTRL_CORE_BASE_ADDR: usize = 0x40010000;

/// Peripheral size for core device on otp_ctrl in top peppermint.
///
/// This is the size (in bytes) of the peripheral's reserved memory area. All
/// memory-mapped registers associated with this peripheral should have an
/// address between #OTP_CTRL_CORE_BASE_ADDR and
/// `OTP_CTRL_CORE_BASE_ADDR + OTP_CTRL_CORE_SIZE_BYTES`.
pub const OTP_CTRL_CORE_SIZE_BYTES: usize = 0x4000;

/// Peripheral base address for prim device on otp_macro in top peppermint.
///
/// This should be used with #mmio_region_from_addr to access the memory-mapped
/// registers associated with the peripheral (usually via a DIF).
pub const OTP_MACRO_PRIM_BASE_ADDR: usize = 0x40020000;

/// Peripheral size for prim device on otp_macro in top peppermint.
///
/// This is the size (in bytes) of the peripheral's reserved memory area. All
/// memory-mapped registers associated with this peripheral should have an
/// address between #OTP_MACRO_PRIM_BASE_ADDR and
/// `OTP_MACRO_PRIM_BASE_ADDR + OTP_MACRO_PRIM_SIZE_BYTES`.
pub const OTP_MACRO_PRIM_SIZE_BYTES: usize = 0x20;

/// Peripheral base address for regs device on lc_ctrl in top peppermint.
///
/// This should be used with #mmio_region_from_addr to access the memory-mapped
/// registers associated with the peripheral (usually via a DIF).
pub const LC_CTRL_REGS_BASE_ADDR: usize = 0x40030000;

/// Peripheral size for regs device on lc_ctrl in top peppermint.
///
/// This is the size (in bytes) of the peripheral's reserved memory area. All
/// memory-mapped registers associated with this peripheral should have an
/// address between #LC_CTRL_REGS_BASE_ADDR and
/// `LC_CTRL_REGS_BASE_ADDR + LC_CTRL_REGS_SIZE_BYTES`.
pub const LC_CTRL_REGS_SIZE_BYTES: usize = 0x100;

/// Peripheral base address for aes in top peppermint.
///
/// This should be used with #mmio_region_from_addr to access the memory-mapped
/// registers associated with the peripheral (usually via a DIF).
pub const AES_BASE_ADDR: usize = 0x40100000;

/// Peripheral size for aes in top peppermint.
///
/// This is the size (in bytes) of the peripheral's reserved memory area. All
/// memory-mapped registers associated with this peripheral should have an
/// address between #AES_BASE_ADDR and
/// `AES_BASE_ADDR + AES_SIZE_BYTES`.
pub const AES_SIZE_BYTES: usize = 0x100;

/// Peripheral base address for hmac in top peppermint.
///
/// This should be used with #mmio_region_from_addr to access the memory-mapped
/// registers associated with the peripheral (usually via a DIF).
pub const HMAC_BASE_ADDR: usize = 0x40110000;

/// Peripheral size for hmac in top peppermint.
///
/// This is the size (in bytes) of the peripheral's reserved memory area. All
/// memory-mapped registers associated with this peripheral should have an
/// address between #HMAC_BASE_ADDR and
/// `HMAC_BASE_ADDR + HMAC_SIZE_BYTES`.
pub const HMAC_SIZE_BYTES: usize = 0x2000;

/// Peripheral base address for kmac in top peppermint.
///
/// This should be used with #mmio_region_from_addr to access the memory-mapped
/// registers associated with the peripheral (usually via a DIF).
pub const KMAC_BASE_ADDR: usize = 0x40120000;

/// Peripheral size for kmac in top peppermint.
///
/// This is the size (in bytes) of the peripheral's reserved memory area. All
/// memory-mapped registers associated with this peripheral should have an
/// address between #KMAC_BASE_ADDR and
/// `KMAC_BASE_ADDR + KMAC_SIZE_BYTES`.
pub const KMAC_SIZE_BYTES: usize = 0x1000;

/// Peripheral base address for otbn in top peppermint.
///
/// This should be used with #mmio_region_from_addr to access the memory-mapped
/// registers associated with the peripheral (usually via a DIF).
pub const OTBN_BASE_ADDR: usize = 0x40130000;

/// Peripheral size for otbn in top peppermint.
///
/// This is the size (in bytes) of the peripheral's reserved memory area. All
/// memory-mapped registers associated with this peripheral should have an
/// address between #OTBN_BASE_ADDR and
/// `OTBN_BASE_ADDR + OTBN_SIZE_BYTES`.
pub const OTBN_SIZE_BYTES: usize = 0x10000;

/// Peripheral base address for keymgr_dpe in top peppermint.
///
/// This should be used with #mmio_region_from_addr to access the memory-mapped
/// registers associated with the peripheral (usually via a DIF).
pub const KEYMGR_DPE_BASE_ADDR: usize = 0x40140000;

/// Peripheral size for keymgr_dpe in top peppermint.
///
/// This is the size (in bytes) of the peripheral's reserved memory area. All
/// memory-mapped registers associated with this peripheral should have an
/// address between #KEYMGR_DPE_BASE_ADDR and
/// `KEYMGR_DPE_BASE_ADDR + KEYMGR_DPE_SIZE_BYTES`.
pub const KEYMGR_DPE_SIZE_BYTES: usize = 0x100;

/// Peripheral base address for csrng in top peppermint.
///
/// This should be used with #mmio_region_from_addr to access the memory-mapped
/// registers associated with the peripheral (usually via a DIF).
pub const CSRNG_BASE_ADDR: usize = 0x40150000;

/// Peripheral size for csrng in top peppermint.
///
/// This is the size (in bytes) of the peripheral's reserved memory area. All
/// memory-mapped registers associated with this peripheral should have an
/// address between #CSRNG_BASE_ADDR and
/// `CSRNG_BASE_ADDR + CSRNG_SIZE_BYTES`.
pub const CSRNG_SIZE_BYTES: usize = 0x80;

/// Peripheral base address for entropy_src in top peppermint.
///
/// This should be used with #mmio_region_from_addr to access the memory-mapped
/// registers associated with the peripheral (usually via a DIF).
pub const ENTROPY_SRC_BASE_ADDR: usize = 0x40160000;

/// Peripheral size for entropy_src in top peppermint.
///
/// This is the size (in bytes) of the peripheral's reserved memory area. All
/// memory-mapped registers associated with this peripheral should have an
/// address between #ENTROPY_SRC_BASE_ADDR and
/// `ENTROPY_SRC_BASE_ADDR + ENTROPY_SRC_SIZE_BYTES`.
pub const ENTROPY_SRC_SIZE_BYTES: usize = 0x100;

/// Peripheral base address for edn0 in top peppermint.
///
/// This should be used with #mmio_region_from_addr to access the memory-mapped
/// registers associated with the peripheral (usually via a DIF).
pub const EDN0_BASE_ADDR: usize = 0x40170000;

/// Peripheral size for edn0 in top peppermint.
///
/// This is the size (in bytes) of the peripheral's reserved memory area. All
/// memory-mapped registers associated with this peripheral should have an
/// address between #EDN0_BASE_ADDR and
/// `EDN0_BASE_ADDR + EDN0_SIZE_BYTES`.
pub const EDN0_SIZE_BYTES: usize = 0x80;

/// Peripheral base address for edn1 in top peppermint.
///
/// This should be used with #mmio_region_from_addr to access the memory-mapped
/// registers associated with the peripheral (usually via a DIF).
pub const EDN1_BASE_ADDR: usize = 0x40180000;

/// Peripheral size for edn1 in top peppermint.
///
/// This is the size (in bytes) of the peripheral's reserved memory area. All
/// memory-mapped registers associated with this peripheral should have an
/// address between #EDN1_BASE_ADDR and
/// `EDN1_BASE_ADDR + EDN1_SIZE_BYTES`.
pub const EDN1_SIZE_BYTES: usize = 0x80;

/// Peripheral base address for regs device on sram_ctrl_main in top peppermint.
///
/// This should be used with #mmio_region_from_addr to access the memory-mapped
/// registers associated with the peripheral (usually via a DIF).
pub const SRAM_CTRL_MAIN_REGS_BASE_ADDR: usize = 0x40200000;

/// Peripheral size for regs device on sram_ctrl_main in top peppermint.
///
/// This is the size (in bytes) of the peripheral's reserved memory area. All
/// memory-mapped registers associated with this peripheral should have an
/// address between #SRAM_CTRL_MAIN_REGS_BASE_ADDR and
/// `SRAM_CTRL_MAIN_REGS_BASE_ADDR + SRAM_CTRL_MAIN_REGS_SIZE_BYTES`.
pub const SRAM_CTRL_MAIN_REGS_SIZE_BYTES: usize = 0x40;

/// Peripheral base address for regs device on rom_ctrl in top peppermint.
///
/// This should be used with #mmio_region_from_addr to access the memory-mapped
/// registers associated with the peripheral (usually via a DIF).
pub const ROM_CTRL_REGS_BASE_ADDR: usize = 0x40210000;

/// Peripheral size for regs device on rom_ctrl in top peppermint.
///
/// This is the size (in bytes) of the peripheral's reserved memory area. All
/// memory-mapped registers associated with this peripheral should have an
/// address between #ROM_CTRL_REGS_BASE_ADDR and
/// `ROM_CTRL_REGS_BASE_ADDR + ROM_CTRL_REGS_SIZE_BYTES`.
pub const ROM_CTRL_REGS_SIZE_BYTES: usize = 0x80;

/// Peripheral base address for cfg device on rv_core_ibex in top peppermint.
///
/// This should be used with #mmio_region_from_addr to access the memory-mapped
/// registers associated with the peripheral (usually via a DIF).
pub const RV_CORE_IBEX_CFG_BASE_ADDR: usize = 0x40220000;

/// Peripheral size for cfg device on rv_core_ibex in top peppermint.
///
/// This is the size (in bytes) of the peripheral's reserved memory area. All
/// memory-mapped registers associated with this peripheral should have an
/// address between #RV_CORE_IBEX_CFG_BASE_ADDR and
/// `RV_CORE_IBEX_CFG_BASE_ADDR + RV_CORE_IBEX_CFG_SIZE_BYTES`.
pub const RV_CORE_IBEX_CFG_SIZE_BYTES: usize = 0x800;

/// Peripheral base address for regs device on rv_dm in top peppermint.
///
/// This should be used with #mmio_region_from_addr to access the memory-mapped
/// registers associated with the peripheral (usually via a DIF).
pub const RV_DM_REGS_BASE_ADDR: usize = 0x40230000;

/// Peripheral size for regs device on rv_dm in top peppermint.
///
/// This is the size (in bytes) of the peripheral's reserved memory area. All
/// memory-mapped registers associated with this peripheral should have an
/// address between #RV_DM_REGS_BASE_ADDR and
/// `RV_DM_REGS_BASE_ADDR + RV_DM_REGS_SIZE_BYTES`.
pub const RV_DM_REGS_SIZE_BYTES: usize = 0x10;

/// Peripheral base address for mem device on rv_dm in top peppermint.
///
/// This should be used with #mmio_region_from_addr to access the memory-mapped
/// registers associated with the peripheral (usually via a DIF).
pub const RV_DM_MEM_BASE_ADDR: usize = 0x10000;

/// Peripheral size for mem device on rv_dm in top peppermint.
///
/// This is the size (in bytes) of the peripheral's reserved memory area. All
/// memory-mapped registers associated with this peripheral should have an
/// address between #RV_DM_MEM_BASE_ADDR and
/// `RV_DM_MEM_BASE_ADDR + RV_DM_MEM_SIZE_BYTES`.
pub const RV_DM_MEM_SIZE_BYTES: usize = 0x1000;

/// Peripheral base address for dma in top peppermint.
///
/// This should be used with #mmio_region_from_addr to access the memory-mapped
/// registers associated with the peripheral (usually via a DIF).
pub const DMA_BASE_ADDR: usize = 0x40300000;

/// Peripheral size for dma in top peppermint.
///
/// This is the size (in bytes) of the peripheral's reserved memory area. All
/// memory-mapped registers associated with this peripheral should have an
/// address between #DMA_BASE_ADDR and
/// `DMA_BASE_ADDR + DMA_SIZE_BYTES`.
pub const DMA_SIZE_BYTES: usize = 0x200;

/// Peripheral base address for core device on mbx0 in top peppermint.
///
/// This should be used with #mmio_region_from_addr to access the memory-mapped
/// registers associated with the peripheral (usually via a DIF).
pub const MBX0_CORE_BASE_ADDR: usize = 0x40310000;

/// Peripheral size for core device on mbx0 in top peppermint.
///
/// This is the size (in bytes) of the peripheral's reserved memory area. All
/// memory-mapped registers associated with this peripheral should have an
/// address between #MBX0_CORE_BASE_ADDR and
/// `MBX0_CORE_BASE_ADDR + MBX0_CORE_SIZE_BYTES`.
pub const MBX0_CORE_SIZE_BYTES: usize = 0x80;

/// Peripheral base address for core device on mbx1 in top peppermint.
///
/// This should be used with #mmio_region_from_addr to access the memory-mapped
/// registers associated with the peripheral (usually via a DIF).
pub const MBX1_CORE_BASE_ADDR: usize = 0x40320000;

/// Peripheral size for core device on mbx1 in top peppermint.
///
/// This is the size (in bytes) of the peripheral's reserved memory area. All
/// memory-mapped registers associated with this peripheral should have an
/// address between #MBX1_CORE_BASE_ADDR and
/// `MBX1_CORE_BASE_ADDR + MBX1_CORE_SIZE_BYTES`.
pub const MBX1_CORE_SIZE_BYTES: usize = 0x80;

/// Peripheral base address for pwrmgr in top peppermint.
///
/// This should be used with #mmio_region_from_addr to access the memory-mapped
/// registers associated with the peripheral (usually via a DIF).
pub const PWRMGR_BASE_ADDR: usize = 0x41000000;

/// Peripheral size for pwrmgr in top peppermint.
///
/// This is the size (in bytes) of the peripheral's reserved memory area. All
/// memory-mapped registers associated with this peripheral should have an
/// address between #PWRMGR_BASE_ADDR and
/// `PWRMGR_BASE_ADDR + PWRMGR_SIZE_BYTES`.
pub const PWRMGR_SIZE_BYTES: usize = 0x80;

/// Peripheral base address for rstmgr in top peppermint.
///
/// This should be used with #mmio_region_from_addr to access the memory-mapped
/// registers associated with the peripheral (usually via a DIF).
pub const RSTMGR_BASE_ADDR: usize = 0x41010000;

/// Peripheral size for rstmgr in top peppermint.
///
/// This is the size (in bytes) of the peripheral's reserved memory area. All
/// memory-mapped registers associated with this peripheral should have an
/// address between #RSTMGR_BASE_ADDR and
/// `RSTMGR_BASE_ADDR + RSTMGR_SIZE_BYTES`.
pub const RSTMGR_SIZE_BYTES: usize = 0x40;

/// Peripheral base address for clkmgr in top peppermint.
///
/// This should be used with #mmio_region_from_addr to access the memory-mapped
/// registers associated with the peripheral (usually via a DIF).
pub const CLKMGR_BASE_ADDR: usize = 0x41020000;

/// Peripheral size for clkmgr in top peppermint.
///
/// This is the size (in bytes) of the peripheral's reserved memory area. All
/// memory-mapped registers associated with this peripheral should have an
/// address between #CLKMGR_BASE_ADDR and
/// `CLKMGR_BASE_ADDR + CLKMGR_SIZE_BYTES`.
pub const CLKMGR_SIZE_BYTES: usize = 0x40;

/// Peripheral base address for alert_handler in top peppermint.
///
/// This should be used with #mmio_region_from_addr to access the memory-mapped
/// registers associated with the peripheral (usually via a DIF).
pub const ALERT_HANDLER_BASE_ADDR: usize = 0x41040000;

/// Peripheral size for alert_handler in top peppermint.
///
/// This is the size (in bytes) of the peripheral's reserved memory area. All
/// memory-mapped registers associated with this peripheral should have an
/// address between #ALERT_HANDLER_BASE_ADDR and
/// `ALERT_HANDLER_BASE_ADDR + ALERT_HANDLER_SIZE_BYTES`.
pub const ALERT_HANDLER_SIZE_BYTES: usize = 0x800;

/// Peripheral base address for regs device on sram_ctrl_ret in top peppermint.
///
/// This should be used with #mmio_region_from_addr to access the memory-mapped
/// registers associated with the peripheral (usually via a DIF).
pub const SRAM_CTRL_RET_REGS_BASE_ADDR: usize = 0x41050000;

/// Peripheral size for regs device on sram_ctrl_ret in top peppermint.
///
/// This is the size (in bytes) of the peripheral's reserved memory area. All
/// memory-mapped registers associated with this peripheral should have an
/// address between #SRAM_CTRL_RET_REGS_BASE_ADDR and
/// `SRAM_CTRL_RET_REGS_BASE_ADDR + SRAM_CTRL_RET_REGS_SIZE_BYTES`.
pub const SRAM_CTRL_RET_REGS_SIZE_BYTES: usize = 0x40;

/// Peripheral base address for rv_plic in top peppermint.
///
/// This should be used with #mmio_region_from_addr to access the memory-mapped
/// registers associated with the peripheral (usually via a DIF).
pub const RV_PLIC_BASE_ADDR: usize = 0x48000000;

/// Peripheral size for rv_plic in top peppermint.
///
/// This is the size (in bytes) of the peripheral's reserved memory area. All
/// memory-mapped registers associated with this peripheral should have an
/// address between #RV_PLIC_BASE_ADDR and
/// `RV_PLIC_BASE_ADDR + RV_PLIC_SIZE_BYTES`.
pub const RV_PLIC_SIZE_BYTES: usize = 0x8000000;

/// Memory base address for ram memory on sram_ctrl_main in top peppermint.
pub const SRAM_CTRL_MAIN_RAM_BASE_ADDR: usize = 0x10000000;

/// Memory size for ram memory on sram_ctrl_main in top peppermint.
pub const SRAM_CTRL_MAIN_RAM_SIZE_BYTES: usize = 0x30000;

/// Memory base address for rom memory on rom_ctrl in top peppermint.
pub const ROM_CTRL_ROM_BASE_ADDR: usize = 0x40000;

/// Memory size for rom memory on rom_ctrl in top peppermint.
pub const ROM_CTRL_ROM_SIZE_BYTES: usize = 0x20000;

/// Memory base address for ram memory on sram_ctrl_ret in top peppermint.
pub const SRAM_CTRL_RET_RAM_BASE_ADDR: usize = 0x41100000;

/// Memory size for ram memory on sram_ctrl_ret in top peppermint.
pub const SRAM_CTRL_RET_RAM_SIZE_BYTES: usize = 0x2000;

/// Memory base address for ctn memory on ahb_bridge in top peppermint.
pub const AHB_BRIDGE_CTN_BASE_ADDR: usize = 0x80000000;

/// Memory size for ctn memory on ahb_bridge in top peppermint.
pub const AHB_BRIDGE_CTN_SIZE_BYTES: usize = 0x80000000;

/// PLIC Interrupt Source Peripheral.
///
/// Enumeration used to determine which peripheral asserted the corresponding
/// interrupt.
#[derive(Copy, Clone, PartialEq, Eq)]
#[repr(u32)]
pub enum PlicPeripheral {
    /// Unknown Peripheral
    Unknown = 0,
    /// rv_timer
    RvTimer = 1,
    /// otp_ctrl
    OtpCtrl = 2,
    /// hmac
    Hmac = 3,
    /// kmac
    Kmac = 4,
    /// otbn
    Otbn = 5,
    /// keymgr_dpe
    KeymgrDpe = 6,
    /// csrng
    Csrng = 7,
    /// entropy_src
    EntropySrc = 8,
    /// edn0
    Edn0 = 9,
    /// edn1
    Edn1 = 10,
    /// dma
    Dma = 11,
    /// mbx0
    Mbx0 = 12,
    /// mbx1
    Mbx1 = 13,
    /// pwrmgr
    Pwrmgr = 14,
    /// alert_handler
    AlertHandler = 15,
}

impl TryFrom<u32> for PlicPeripheral {
    type Error = u32;
    fn try_from(val: u32) -> Result<Self, Self::Error> {
        match val {
            0 => Ok(Self::Unknown),
            1 => Ok(Self::RvTimer),
            2 => Ok(Self::OtpCtrl),
            3 => Ok(Self::Hmac),
            4 => Ok(Self::Kmac),
            5 => Ok(Self::Otbn),
            6 => Ok(Self::KeymgrDpe),
            7 => Ok(Self::Csrng),
            8 => Ok(Self::EntropySrc),
            9 => Ok(Self::Edn0),
            10 => Ok(Self::Edn1),
            11 => Ok(Self::Dma),
            12 => Ok(Self::Mbx0),
            13 => Ok(Self::Mbx1),
            14 => Ok(Self::Pwrmgr),
            15 => Ok(Self::AlertHandler),
            _ => Err(val),
        }
    }
}

/// PLIC Interrupt Source.
///
/// Enumeration of all PLIC interrupt sources. The interrupt sources belonging to
/// the same peripheral are guaranteed to be consecutive.
#[derive(Copy, Clone, PartialEq, Eq)]
#[repr(u32)]
pub enum PlicIrqId {
    /// No Interrupt
    None = 0,
    /// rv_timer_timer_expired_hart0_timer0
    RvTimerTimerExpiredHart0Timer0 = 1,
    /// otp_ctrl_otp_operation_done
    OtpCtrlOtpOperationDone = 2,
    /// otp_ctrl_otp_error
    OtpCtrlOtpError = 3,
    /// hmac_hmac_done
    HmacHmacDone = 4,
    /// hmac_fifo_empty
    HmacFifoEmpty = 5,
    /// hmac_hmac_err
    HmacHmacErr = 6,
    /// kmac_kmac_done
    KmacKmacDone = 7,
    /// kmac_fifo_empty
    KmacFifoEmpty = 8,
    /// kmac_kmac_err
    KmacKmacErr = 9,
    /// otbn_done
    OtbnDone = 10,
    /// keymgr_dpe_op_done
    KeymgrDpeOpDone = 11,
    /// csrng_cs_cmd_req_done
    CsrngCsCmdReqDone = 12,
    /// csrng_cs_entropy_req
    CsrngCsEntropyReq = 13,
    /// csrng_cs_hw_inst_exc
    CsrngCsHwInstExc = 14,
    /// csrng_cs_fatal_err
    CsrngCsFatalErr = 15,
    /// entropy_src_es_entropy_valid
    EntropySrcEsEntropyValid = 16,
    /// entropy_src_es_health_test_failed
    EntropySrcEsHealthTestFailed = 17,
    /// entropy_src_es_observe_fifo_ready
    EntropySrcEsObserveFifoReady = 18,
    /// entropy_src_es_fatal_err
    EntropySrcEsFatalErr = 19,
    /// edn0_edn_cmd_req_done
    Edn0EdnCmdReqDone = 20,
    /// edn0_edn_fatal_err
    Edn0EdnFatalErr = 21,
    /// edn1_edn_cmd_req_done
    Edn1EdnCmdReqDone = 22,
    /// edn1_edn_fatal_err
    Edn1EdnFatalErr = 23,
    /// dma_dma_done
    DmaDmaDone = 24,
    /// dma_dma_chunk_done
    DmaDmaChunkDone = 25,
    /// dma_dma_error
    DmaDmaError = 26,
    /// mbx0_mbx_ready
    Mbx0MbxReady = 27,
    /// mbx0_mbx_abort
    Mbx0MbxAbort = 28,
    /// mbx0_mbx_error
    Mbx0MbxError = 29,
    /// mbx1_mbx_ready
    Mbx1MbxReady = 30,
    /// mbx1_mbx_abort
    Mbx1MbxAbort = 31,
    /// mbx1_mbx_error
    Mbx1MbxError = 32,
    /// pwrmgr_wakeup
    PwrmgrWakeup = 33,
    /// alert_handler_classa
    AlertHandlerClassa = 34,
    /// alert_handler_classb
    AlertHandlerClassb = 35,
    /// alert_handler_classc
    AlertHandlerClassc = 36,
    /// alert_handler_classd
    AlertHandlerClassd = 37,
    /// soc_irq_0
    SocIrq0 = 38,
    /// soc_irq_1
    SocIrq1 = 39,
    /// soc_irq_2
    SocIrq2 = 40,
    /// soc_irq_3
    SocIrq3 = 41,
}

impl TryFrom<u32> for PlicIrqId {
    type Error = u32;
    fn try_from(val: u32) -> Result<Self, Self::Error> {
        match val {
            0 => Ok(Self::None),
            1 => Ok(Self::RvTimerTimerExpiredHart0Timer0),
            2 => Ok(Self::OtpCtrlOtpOperationDone),
            3 => Ok(Self::OtpCtrlOtpError),
            4 => Ok(Self::HmacHmacDone),
            5 => Ok(Self::HmacFifoEmpty),
            6 => Ok(Self::HmacHmacErr),
            7 => Ok(Self::KmacKmacDone),
            8 => Ok(Self::KmacFifoEmpty),
            9 => Ok(Self::KmacKmacErr),
            10 => Ok(Self::OtbnDone),
            11 => Ok(Self::KeymgrDpeOpDone),
            12 => Ok(Self::CsrngCsCmdReqDone),
            13 => Ok(Self::CsrngCsEntropyReq),
            14 => Ok(Self::CsrngCsHwInstExc),
            15 => Ok(Self::CsrngCsFatalErr),
            16 => Ok(Self::EntropySrcEsEntropyValid),
            17 => Ok(Self::EntropySrcEsHealthTestFailed),
            18 => Ok(Self::EntropySrcEsObserveFifoReady),
            19 => Ok(Self::EntropySrcEsFatalErr),
            20 => Ok(Self::Edn0EdnCmdReqDone),
            21 => Ok(Self::Edn0EdnFatalErr),
            22 => Ok(Self::Edn1EdnCmdReqDone),
            23 => Ok(Self::Edn1EdnFatalErr),
            24 => Ok(Self::DmaDmaDone),
            25 => Ok(Self::DmaDmaChunkDone),
            26 => Ok(Self::DmaDmaError),
            27 => Ok(Self::Mbx0MbxReady),
            28 => Ok(Self::Mbx0MbxAbort),
            29 => Ok(Self::Mbx0MbxError),
            30 => Ok(Self::Mbx1MbxReady),
            31 => Ok(Self::Mbx1MbxAbort),
            32 => Ok(Self::Mbx1MbxError),
            33 => Ok(Self::PwrmgrWakeup),
            34 => Ok(Self::AlertHandlerClassa),
            35 => Ok(Self::AlertHandlerClassb),
            36 => Ok(Self::AlertHandlerClassc),
            37 => Ok(Self::AlertHandlerClassd),
            38 => Ok(Self::SocIrq0),
            39 => Ok(Self::SocIrq1),
            40 => Ok(Self::SocIrq2),
            41 => Ok(Self::SocIrq3),
            _ => Err(val),
        }
    }
}

/// PLIC Interrupt Target.
///
/// Enumeration used to determine which set of IE, CC, threshold registers to
/// access for a given interrupt target.
#[derive(Copy, Clone, PartialEq, Eq)]
#[repr(u32)]
pub enum PlicTarget {
    /// Ibex Core 0
    Ibex0 = 0,
}

/// PLIC Interrupt Source to Peripheral Map
///
/// This array is a mapping from `PlicIrqId` to
/// `PlicPeripheral`.
pub const PLIC_INTERRUPT_FOR_PERIPHERAL: [PlicPeripheral; 42] = [
    // None -> PlicPeripheral::Unknown
    PlicPeripheral::Unknown,
    // RvTimerTimerExpiredHart0Timer0 -> PlicPeripheral::RvTimer
    PlicPeripheral::RvTimer,
    // OtpCtrlOtpOperationDone -> PlicPeripheral::OtpCtrl
    PlicPeripheral::OtpCtrl,
    // OtpCtrlOtpError -> PlicPeripheral::OtpCtrl
    PlicPeripheral::OtpCtrl,
    // HmacHmacDone -> PlicPeripheral::Hmac
    PlicPeripheral::Hmac,
    // HmacFifoEmpty -> PlicPeripheral::Hmac
    PlicPeripheral::Hmac,
    // HmacHmacErr -> PlicPeripheral::Hmac
    PlicPeripheral::Hmac,
    // KmacKmacDone -> PlicPeripheral::Kmac
    PlicPeripheral::Kmac,
    // KmacFifoEmpty -> PlicPeripheral::Kmac
    PlicPeripheral::Kmac,
    // KmacKmacErr -> PlicPeripheral::Kmac
    PlicPeripheral::Kmac,
    // OtbnDone -> PlicPeripheral::Otbn
    PlicPeripheral::Otbn,
    // KeymgrDpeOpDone -> PlicPeripheral::KeymgrDpe
    PlicPeripheral::KeymgrDpe,
    // CsrngCsCmdReqDone -> PlicPeripheral::Csrng
    PlicPeripheral::Csrng,
    // CsrngCsEntropyReq -> PlicPeripheral::Csrng
    PlicPeripheral::Csrng,
    // CsrngCsHwInstExc -> PlicPeripheral::Csrng
    PlicPeripheral::Csrng,
    // CsrngCsFatalErr -> PlicPeripheral::Csrng
    PlicPeripheral::Csrng,
    // EntropySrcEsEntropyValid -> PlicPeripheral::EntropySrc
    PlicPeripheral::EntropySrc,
    // EntropySrcEsHealthTestFailed -> PlicPeripheral::EntropySrc
    PlicPeripheral::EntropySrc,
    // EntropySrcEsObserveFifoReady -> PlicPeripheral::EntropySrc
    PlicPeripheral::EntropySrc,
    // EntropySrcEsFatalErr -> PlicPeripheral::EntropySrc
    PlicPeripheral::EntropySrc,
    // Edn0EdnCmdReqDone -> PlicPeripheral::Edn0
    PlicPeripheral::Edn0,
    // Edn0EdnFatalErr -> PlicPeripheral::Edn0
    PlicPeripheral::Edn0,
    // Edn1EdnCmdReqDone -> PlicPeripheral::Edn1
    PlicPeripheral::Edn1,
    // Edn1EdnFatalErr -> PlicPeripheral::Edn1
    PlicPeripheral::Edn1,
    // DmaDmaDone -> PlicPeripheral::Dma
    PlicPeripheral::Dma,
    // DmaDmaChunkDone -> PlicPeripheral::Dma
    PlicPeripheral::Dma,
    // DmaDmaError -> PlicPeripheral::Dma
    PlicPeripheral::Dma,
    // Mbx0MbxReady -> PlicPeripheral::Mbx0
    PlicPeripheral::Mbx0,
    // Mbx0MbxAbort -> PlicPeripheral::Mbx0
    PlicPeripheral::Mbx0,
    // Mbx0MbxError -> PlicPeripheral::Mbx0
    PlicPeripheral::Mbx0,
    // Mbx1MbxReady -> PlicPeripheral::Mbx1
    PlicPeripheral::Mbx1,
    // Mbx1MbxAbort -> PlicPeripheral::Mbx1
    PlicPeripheral::Mbx1,
    // Mbx1MbxError -> PlicPeripheral::Mbx1
    PlicPeripheral::Mbx1,
    // PwrmgrWakeup -> PlicPeripheral::Pwrmgr
    PlicPeripheral::Pwrmgr,
    // AlertHandlerClassa -> PlicPeripheral::AlertHandler
    PlicPeripheral::AlertHandler,
    // AlertHandlerClassb -> PlicPeripheral::AlertHandler
    PlicPeripheral::AlertHandler,
    // AlertHandlerClassc -> PlicPeripheral::AlertHandler
    PlicPeripheral::AlertHandler,
    // AlertHandlerClassd -> PlicPeripheral::AlertHandler
    PlicPeripheral::AlertHandler,
    // SocIrq0 -> PlicPeripheral::Unknown
    PlicPeripheral::Unknown,
    // SocIrq1 -> PlicPeripheral::Unknown
    PlicPeripheral::Unknown,
    // SocIrq2 -> PlicPeripheral::Unknown
    PlicPeripheral::Unknown,
    // SocIrq3 -> PlicPeripheral::Unknown
    PlicPeripheral::Unknown,
];

/// Alert Handler Source Peripheral.
///
/// Enumeration used to determine which peripheral asserted the corresponding
/// alert.
#[derive(Copy, Clone, PartialEq, Eq)]
#[repr(u32)]
pub enum AlertPeripheral {
    /// External Peripheral
    External = 0,
    /// rv_timer
    RvTimer = 1,
    /// otp_ctrl
    OtpCtrl = 2,
    /// lc_ctrl
    LcCtrl = 3,
    /// aes
    Aes = 4,
    /// hmac
    Hmac = 5,
    /// kmac
    Kmac = 6,
    /// otbn
    Otbn = 7,
    /// keymgr_dpe
    KeymgrDpe = 8,
    /// csrng
    Csrng = 9,
    /// entropy_src
    EntropySrc = 10,
    /// edn0
    Edn0 = 11,
    /// edn1
    Edn1 = 12,
    /// sram_ctrl_main
    SramCtrlMain = 13,
    /// rom_ctrl
    RomCtrl = 14,
    /// rv_core_ibex
    RvCoreIbex = 15,
    /// rv_dm
    RvDm = 16,
    /// dma
    Dma = 17,
    /// mbx0
    Mbx0 = 18,
    /// mbx1
    Mbx1 = 19,
    /// pwrmgr
    Pwrmgr = 20,
    /// rstmgr
    Rstmgr = 21,
    /// clkmgr
    Clkmgr = 22,
    /// sram_ctrl_ret
    SramCtrlRet = 23,
    /// rv_plic
    RvPlic = 24,
}

/// Alert Handler Alert Source.
///
/// Enumeration of all Alert Handler Alert Sources. The alert sources belonging to
/// the same peripheral are guaranteed to be consecutive.
#[derive(Copy, Clone, PartialEq, Eq)]
#[repr(u32)]
pub enum AlertId {
    /// rv_timer_fatal_fault
    RvTimerFatalFault = 0,
    /// otp_ctrl_fatal_macro_error
    OtpCtrlFatalMacroError = 1,
    /// otp_ctrl_fatal_check_error
    OtpCtrlFatalCheckError = 2,
    /// otp_ctrl_fatal_bus_integ_error
    OtpCtrlFatalBusIntegError = 3,
    /// otp_ctrl_fatal_prim_otp_alert
    OtpCtrlFatalPrimOtpAlert = 4,
    /// otp_ctrl_recov_prim_otp_alert
    OtpCtrlRecovPrimOtpAlert = 5,
    /// lc_ctrl_fatal_prog_error
    LcCtrlFatalProgError = 6,
    /// lc_ctrl_fatal_state_error
    LcCtrlFatalStateError = 7,
    /// lc_ctrl_fatal_bus_integ_error
    LcCtrlFatalBusIntegError = 8,
    /// aes_recov_ctrl_update_err
    AesRecovCtrlUpdateErr = 9,
    /// aes_fatal_fault
    AesFatalFault = 10,
    /// hmac_fatal_fault
    HmacFatalFault = 11,
    /// kmac_recov_operation_err
    KmacRecovOperationErr = 12,
    /// kmac_fatal_fault_err
    KmacFatalFaultErr = 13,
    /// otbn_fatal
    OtbnFatal = 14,
    /// otbn_recov
    OtbnRecov = 15,
    /// keymgr_dpe_recov_operation_err
    KeymgrDpeRecovOperationErr = 16,
    /// keymgr_dpe_fatal_fault_err
    KeymgrDpeFatalFaultErr = 17,
    /// csrng_recov_alert
    CsrngRecovAlert = 18,
    /// csrng_fatal_alert
    CsrngFatalAlert = 19,
    /// entropy_src_recov_alert
    EntropySrcRecovAlert = 20,
    /// entropy_src_fatal_alert
    EntropySrcFatalAlert = 21,
    /// edn0_recov_alert
    Edn0RecovAlert = 22,
    /// edn0_fatal_alert
    Edn0FatalAlert = 23,
    /// edn1_recov_alert
    Edn1RecovAlert = 24,
    /// edn1_fatal_alert
    Edn1FatalAlert = 25,
    /// sram_ctrl_main_fatal_error
    SramCtrlMainFatalError = 26,
    /// rom_ctrl_fatal
    RomCtrlFatal = 27,
    /// rv_core_ibex_fatal_sw_err
    RvCoreIbexFatalSwErr = 28,
    /// rv_core_ibex_recov_sw_err
    RvCoreIbexRecovSwErr = 29,
    /// rv_core_ibex_fatal_hw_err
    RvCoreIbexFatalHwErr = 30,
    /// rv_core_ibex_recov_hw_err
    RvCoreIbexRecovHwErr = 31,
    /// rv_dm_fatal_fault
    RvDmFatalFault = 32,
    /// dma_fatal_fault
    DmaFatalFault = 33,
    /// mbx0_fatal_fault
    Mbx0FatalFault = 34,
    /// mbx0_recov_fault
    Mbx0RecovFault = 35,
    /// mbx1_fatal_fault
    Mbx1FatalFault = 36,
    /// mbx1_recov_fault
    Mbx1RecovFault = 37,
    /// pwrmgr_fatal_fault
    PwrmgrFatalFault = 38,
    /// rstmgr_fatal_fault
    RstmgrFatalFault = 39,
    /// rstmgr_fatal_cnsty_fault
    RstmgrFatalCnstyFault = 40,
    /// clkmgr_recov_fault
    ClkmgrRecovFault = 41,
    /// clkmgr_fatal_fault
    ClkmgrFatalFault = 42,
    /// sram_ctrl_ret_fatal_error
    SramCtrlRetFatalError = 43,
    /// rv_plic_fatal_fault
    RvPlicFatalFault = 44,
    /// incoming_soc_soc_recov_alert_0
    IncomingSocSocRecovAlert0 = 45,
    /// incoming_soc_soc_recov_alert_1
    IncomingSocSocRecovAlert1 = 46,
    /// incoming_soc_soc_recov_alert_2
    IncomingSocSocRecovAlert2 = 47,
    /// incoming_soc_soc_recov_alert_3
    IncomingSocSocRecovAlert3 = 48,
    /// incoming_soc_soc_recov_alert_4
    IncomingSocSocRecovAlert4 = 49,
    /// incoming_soc_soc_recov_alert_5
    IncomingSocSocRecovAlert5 = 50,
    /// incoming_soc_soc_recov_alert_6
    IncomingSocSocRecovAlert6 = 51,
    /// incoming_soc_soc_recov_alert_7
    IncomingSocSocRecovAlert7 = 52,
    /// incoming_soc_soc_recov_alert_8
    IncomingSocSocRecovAlert8 = 53,
    /// incoming_soc_soc_recov_alert_9
    IncomingSocSocRecovAlert9 = 54,
    /// incoming_soc_soc_recov_alert_10
    IncomingSocSocRecovAlert10 = 55,
    /// incoming_soc_soc_recov_alert_11
    IncomingSocSocRecovAlert11 = 56,
    /// incoming_soc_soc_recov_alert_12
    IncomingSocSocRecovAlert12 = 57,
    /// incoming_soc_soc_recov_alert_13
    IncomingSocSocRecovAlert13 = 58,
    /// incoming_soc_soc_recov_alert_14
    IncomingSocSocRecovAlert14 = 59,
    /// incoming_soc_soc_recov_alert_15
    IncomingSocSocRecovAlert15 = 60,
    /// incoming_soc_soc_recov_alert_16
    IncomingSocSocRecovAlert16 = 61,
    /// incoming_soc_soc_recov_alert_17
    IncomingSocSocRecovAlert17 = 62,
    /// incoming_soc_soc_recov_alert_18
    IncomingSocSocRecovAlert18 = 63,
    /// incoming_soc_soc_recov_alert_19
    IncomingSocSocRecovAlert19 = 64,
    /// incoming_soc_soc_recov_alert_20
    IncomingSocSocRecovAlert20 = 65,
    /// incoming_soc_soc_recov_alert_21
    IncomingSocSocRecovAlert21 = 66,
    /// incoming_soc_soc_recov_alert_22
    IncomingSocSocRecovAlert22 = 67,
    /// incoming_soc_soc_recov_alert_23
    IncomingSocSocRecovAlert23 = 68,
    /// incoming_soc_soc_recov_alert_24
    IncomingSocSocRecovAlert24 = 69,
    /// incoming_soc_soc_recov_alert_25
    IncomingSocSocRecovAlert25 = 70,
    /// incoming_soc_soc_recov_alert_26
    IncomingSocSocRecovAlert26 = 71,
    /// incoming_soc_soc_recov_alert_27
    IncomingSocSocRecovAlert27 = 72,
    /// incoming_soc_soc_recov_alert_28
    IncomingSocSocRecovAlert28 = 73,
    /// incoming_soc_soc_recov_alert_29
    IncomingSocSocRecovAlert29 = 74,
    /// incoming_soc_soc_recov_alert_30
    IncomingSocSocRecovAlert30 = 75,
    /// incoming_soc_soc_recov_alert_31
    IncomingSocSocRecovAlert31 = 76,
    /// incoming_soc_soc_fatal_alert_0
    IncomingSocSocFatalAlert0 = 77,
    /// incoming_soc_soc_fatal_alert_1
    IncomingSocSocFatalAlert1 = 78,
    /// incoming_soc_soc_fatal_alert_2
    IncomingSocSocFatalAlert2 = 79,
    /// incoming_soc_soc_fatal_alert_3
    IncomingSocSocFatalAlert3 = 80,
    /// incoming_soc_soc_fatal_alert_4
    IncomingSocSocFatalAlert4 = 81,
    /// incoming_soc_soc_fatal_alert_5
    IncomingSocSocFatalAlert5 = 82,
    /// incoming_soc_soc_fatal_alert_6
    IncomingSocSocFatalAlert6 = 83,
    /// incoming_soc_soc_fatal_alert_7
    IncomingSocSocFatalAlert7 = 84,
}

impl TryFrom<u32> for AlertId {
    type Error = u32;
    fn try_from(val: u32) -> Result<Self, Self::Error> {
        match val {
            0 => Ok(Self::RvTimerFatalFault),
            1 => Ok(Self::OtpCtrlFatalMacroError),
            2 => Ok(Self::OtpCtrlFatalCheckError),
            3 => Ok(Self::OtpCtrlFatalBusIntegError),
            4 => Ok(Self::OtpCtrlFatalPrimOtpAlert),
            5 => Ok(Self::OtpCtrlRecovPrimOtpAlert),
            6 => Ok(Self::LcCtrlFatalProgError),
            7 => Ok(Self::LcCtrlFatalStateError),
            8 => Ok(Self::LcCtrlFatalBusIntegError),
            9 => Ok(Self::AesRecovCtrlUpdateErr),
            10 => Ok(Self::AesFatalFault),
            11 => Ok(Self::HmacFatalFault),
            12 => Ok(Self::KmacRecovOperationErr),
            13 => Ok(Self::KmacFatalFaultErr),
            14 => Ok(Self::OtbnFatal),
            15 => Ok(Self::OtbnRecov),
            16 => Ok(Self::KeymgrDpeRecovOperationErr),
            17 => Ok(Self::KeymgrDpeFatalFaultErr),
            18 => Ok(Self::CsrngRecovAlert),
            19 => Ok(Self::CsrngFatalAlert),
            20 => Ok(Self::EntropySrcRecovAlert),
            21 => Ok(Self::EntropySrcFatalAlert),
            22 => Ok(Self::Edn0RecovAlert),
            23 => Ok(Self::Edn0FatalAlert),
            24 => Ok(Self::Edn1RecovAlert),
            25 => Ok(Self::Edn1FatalAlert),
            26 => Ok(Self::SramCtrlMainFatalError),
            27 => Ok(Self::RomCtrlFatal),
            28 => Ok(Self::RvCoreIbexFatalSwErr),
            29 => Ok(Self::RvCoreIbexRecovSwErr),
            30 => Ok(Self::RvCoreIbexFatalHwErr),
            31 => Ok(Self::RvCoreIbexRecovHwErr),
            32 => Ok(Self::RvDmFatalFault),
            33 => Ok(Self::DmaFatalFault),
            34 => Ok(Self::Mbx0FatalFault),
            35 => Ok(Self::Mbx0RecovFault),
            36 => Ok(Self::Mbx1FatalFault),
            37 => Ok(Self::Mbx1RecovFault),
            38 => Ok(Self::PwrmgrFatalFault),
            39 => Ok(Self::RstmgrFatalFault),
            40 => Ok(Self::RstmgrFatalCnstyFault),
            41 => Ok(Self::ClkmgrRecovFault),
            42 => Ok(Self::ClkmgrFatalFault),
            43 => Ok(Self::SramCtrlRetFatalError),
            44 => Ok(Self::RvPlicFatalFault),
            45 => Ok(Self::IncomingSocSocRecovAlert0),
            46 => Ok(Self::IncomingSocSocRecovAlert1),
            47 => Ok(Self::IncomingSocSocRecovAlert2),
            48 => Ok(Self::IncomingSocSocRecovAlert3),
            49 => Ok(Self::IncomingSocSocRecovAlert4),
            50 => Ok(Self::IncomingSocSocRecovAlert5),
            51 => Ok(Self::IncomingSocSocRecovAlert6),
            52 => Ok(Self::IncomingSocSocRecovAlert7),
            53 => Ok(Self::IncomingSocSocRecovAlert8),
            54 => Ok(Self::IncomingSocSocRecovAlert9),
            55 => Ok(Self::IncomingSocSocRecovAlert10),
            56 => Ok(Self::IncomingSocSocRecovAlert11),
            57 => Ok(Self::IncomingSocSocRecovAlert12),
            58 => Ok(Self::IncomingSocSocRecovAlert13),
            59 => Ok(Self::IncomingSocSocRecovAlert14),
            60 => Ok(Self::IncomingSocSocRecovAlert15),
            61 => Ok(Self::IncomingSocSocRecovAlert16),
            62 => Ok(Self::IncomingSocSocRecovAlert17),
            63 => Ok(Self::IncomingSocSocRecovAlert18),
            64 => Ok(Self::IncomingSocSocRecovAlert19),
            65 => Ok(Self::IncomingSocSocRecovAlert20),
            66 => Ok(Self::IncomingSocSocRecovAlert21),
            67 => Ok(Self::IncomingSocSocRecovAlert22),
            68 => Ok(Self::IncomingSocSocRecovAlert23),
            69 => Ok(Self::IncomingSocSocRecovAlert24),
            70 => Ok(Self::IncomingSocSocRecovAlert25),
            71 => Ok(Self::IncomingSocSocRecovAlert26),
            72 => Ok(Self::IncomingSocSocRecovAlert27),
            73 => Ok(Self::IncomingSocSocRecovAlert28),
            74 => Ok(Self::IncomingSocSocRecovAlert29),
            75 => Ok(Self::IncomingSocSocRecovAlert30),
            76 => Ok(Self::IncomingSocSocRecovAlert31),
            77 => Ok(Self::IncomingSocSocFatalAlert0),
            78 => Ok(Self::IncomingSocSocFatalAlert1),
            79 => Ok(Self::IncomingSocSocFatalAlert2),
            80 => Ok(Self::IncomingSocSocFatalAlert3),
            81 => Ok(Self::IncomingSocSocFatalAlert4),
            82 => Ok(Self::IncomingSocSocFatalAlert5),
            83 => Ok(Self::IncomingSocSocFatalAlert6),
            84 => Ok(Self::IncomingSocSocFatalAlert7),
            _ => Err(val),
        }
    }
}

/// Alert Handler Alert Source to Peripheral Map
///
/// This array is a mapping from `AlertId` to
/// `AlertPeripheral`.
pub const ALERT_FOR_PERIPHERAL: [AlertPeripheral; 85] = [
    // RvTimerFatalFault -> AlertPeripheral::RvTimer
    AlertPeripheral::RvTimer,
    // OtpCtrlFatalMacroError -> AlertPeripheral::OtpCtrl
    AlertPeripheral::OtpCtrl,
    // OtpCtrlFatalCheckError -> AlertPeripheral::OtpCtrl
    AlertPeripheral::OtpCtrl,
    // OtpCtrlFatalBusIntegError -> AlertPeripheral::OtpCtrl
    AlertPeripheral::OtpCtrl,
    // OtpCtrlFatalPrimOtpAlert -> AlertPeripheral::OtpCtrl
    AlertPeripheral::OtpCtrl,
    // OtpCtrlRecovPrimOtpAlert -> AlertPeripheral::OtpCtrl
    AlertPeripheral::OtpCtrl,
    // LcCtrlFatalProgError -> AlertPeripheral::LcCtrl
    AlertPeripheral::LcCtrl,
    // LcCtrlFatalStateError -> AlertPeripheral::LcCtrl
    AlertPeripheral::LcCtrl,
    // LcCtrlFatalBusIntegError -> AlertPeripheral::LcCtrl
    AlertPeripheral::LcCtrl,
    // AesRecovCtrlUpdateErr -> AlertPeripheral::Aes
    AlertPeripheral::Aes,
    // AesFatalFault -> AlertPeripheral::Aes
    AlertPeripheral::Aes,
    // HmacFatalFault -> AlertPeripheral::Hmac
    AlertPeripheral::Hmac,
    // KmacRecovOperationErr -> AlertPeripheral::Kmac
    AlertPeripheral::Kmac,
    // KmacFatalFaultErr -> AlertPeripheral::Kmac
    AlertPeripheral::Kmac,
    // OtbnFatal -> AlertPeripheral::Otbn
    AlertPeripheral::Otbn,
    // OtbnRecov -> AlertPeripheral::Otbn
    AlertPeripheral::Otbn,
    // KeymgrDpeRecovOperationErr -> AlertPeripheral::KeymgrDpe
    AlertPeripheral::KeymgrDpe,
    // KeymgrDpeFatalFaultErr -> AlertPeripheral::KeymgrDpe
    AlertPeripheral::KeymgrDpe,
    // CsrngRecovAlert -> AlertPeripheral::Csrng
    AlertPeripheral::Csrng,
    // CsrngFatalAlert -> AlertPeripheral::Csrng
    AlertPeripheral::Csrng,
    // EntropySrcRecovAlert -> AlertPeripheral::EntropySrc
    AlertPeripheral::EntropySrc,
    // EntropySrcFatalAlert -> AlertPeripheral::EntropySrc
    AlertPeripheral::EntropySrc,
    // Edn0RecovAlert -> AlertPeripheral::Edn0
    AlertPeripheral::Edn0,
    // Edn0FatalAlert -> AlertPeripheral::Edn0
    AlertPeripheral::Edn0,
    // Edn1RecovAlert -> AlertPeripheral::Edn1
    AlertPeripheral::Edn1,
    // Edn1FatalAlert -> AlertPeripheral::Edn1
    AlertPeripheral::Edn1,
    // SramCtrlMainFatalError -> AlertPeripheral::SramCtrlMain
    AlertPeripheral::SramCtrlMain,
    // RomCtrlFatal -> AlertPeripheral::RomCtrl
    AlertPeripheral::RomCtrl,
    // RvCoreIbexFatalSwErr -> AlertPeripheral::RvCoreIbex
    AlertPeripheral::RvCoreIbex,
    // RvCoreIbexRecovSwErr -> AlertPeripheral::RvCoreIbex
    AlertPeripheral::RvCoreIbex,
    // RvCoreIbexFatalHwErr -> AlertPeripheral::RvCoreIbex
    AlertPeripheral::RvCoreIbex,
    // RvCoreIbexRecovHwErr -> AlertPeripheral::RvCoreIbex
    AlertPeripheral::RvCoreIbex,
    // RvDmFatalFault -> AlertPeripheral::RvDm
    AlertPeripheral::RvDm,
    // DmaFatalFault -> AlertPeripheral::Dma
    AlertPeripheral::Dma,
    // Mbx0FatalFault -> AlertPeripheral::Mbx0
    AlertPeripheral::Mbx0,
    // Mbx0RecovFault -> AlertPeripheral::Mbx0
    AlertPeripheral::Mbx0,
    // Mbx1FatalFault -> AlertPeripheral::Mbx1
    AlertPeripheral::Mbx1,
    // Mbx1RecovFault -> AlertPeripheral::Mbx1
    AlertPeripheral::Mbx1,
    // PwrmgrFatalFault -> AlertPeripheral::Pwrmgr
    AlertPeripheral::Pwrmgr,
    // RstmgrFatalFault -> AlertPeripheral::Rstmgr
    AlertPeripheral::Rstmgr,
    // RstmgrFatalCnstyFault -> AlertPeripheral::Rstmgr
    AlertPeripheral::Rstmgr,
    // ClkmgrRecovFault -> AlertPeripheral::Clkmgr
    AlertPeripheral::Clkmgr,
    // ClkmgrFatalFault -> AlertPeripheral::Clkmgr
    AlertPeripheral::Clkmgr,
    // SramCtrlRetFatalError -> AlertPeripheral::SramCtrlRet
    AlertPeripheral::SramCtrlRet,
    // RvPlicFatalFault -> AlertPeripheral::RvPlic
    AlertPeripheral::RvPlic,
    // IncomingSocSocRecovAlert0 -> AlertPeripheral::External
    AlertPeripheral::External,
    // IncomingSocSocRecovAlert1 -> AlertPeripheral::External
    AlertPeripheral::External,
    // IncomingSocSocRecovAlert2 -> AlertPeripheral::External
    AlertPeripheral::External,
    // IncomingSocSocRecovAlert3 -> AlertPeripheral::External
    AlertPeripheral::External,
    // IncomingSocSocRecovAlert4 -> AlertPeripheral::External
    AlertPeripheral::External,
    // IncomingSocSocRecovAlert5 -> AlertPeripheral::External
    AlertPeripheral::External,
    // IncomingSocSocRecovAlert6 -> AlertPeripheral::External
    AlertPeripheral::External,
    // IncomingSocSocRecovAlert7 -> AlertPeripheral::External
    AlertPeripheral::External,
    // IncomingSocSocRecovAlert8 -> AlertPeripheral::External
    AlertPeripheral::External,
    // IncomingSocSocRecovAlert9 -> AlertPeripheral::External
    AlertPeripheral::External,
    // IncomingSocSocRecovAlert10 -> AlertPeripheral::External
    AlertPeripheral::External,
    // IncomingSocSocRecovAlert11 -> AlertPeripheral::External
    AlertPeripheral::External,
    // IncomingSocSocRecovAlert12 -> AlertPeripheral::External
    AlertPeripheral::External,
    // IncomingSocSocRecovAlert13 -> AlertPeripheral::External
    AlertPeripheral::External,
    // IncomingSocSocRecovAlert14 -> AlertPeripheral::External
    AlertPeripheral::External,
    // IncomingSocSocRecovAlert15 -> AlertPeripheral::External
    AlertPeripheral::External,
    // IncomingSocSocRecovAlert16 -> AlertPeripheral::External
    AlertPeripheral::External,
    // IncomingSocSocRecovAlert17 -> AlertPeripheral::External
    AlertPeripheral::External,
    // IncomingSocSocRecovAlert18 -> AlertPeripheral::External
    AlertPeripheral::External,
    // IncomingSocSocRecovAlert19 -> AlertPeripheral::External
    AlertPeripheral::External,
    // IncomingSocSocRecovAlert20 -> AlertPeripheral::External
    AlertPeripheral::External,
    // IncomingSocSocRecovAlert21 -> AlertPeripheral::External
    AlertPeripheral::External,
    // IncomingSocSocRecovAlert22 -> AlertPeripheral::External
    AlertPeripheral::External,
    // IncomingSocSocRecovAlert23 -> AlertPeripheral::External
    AlertPeripheral::External,
    // IncomingSocSocRecovAlert24 -> AlertPeripheral::External
    AlertPeripheral::External,
    // IncomingSocSocRecovAlert25 -> AlertPeripheral::External
    AlertPeripheral::External,
    // IncomingSocSocRecovAlert26 -> AlertPeripheral::External
    AlertPeripheral::External,
    // IncomingSocSocRecovAlert27 -> AlertPeripheral::External
    AlertPeripheral::External,
    // IncomingSocSocRecovAlert28 -> AlertPeripheral::External
    AlertPeripheral::External,
    // IncomingSocSocRecovAlert29 -> AlertPeripheral::External
    AlertPeripheral::External,
    // IncomingSocSocRecovAlert30 -> AlertPeripheral::External
    AlertPeripheral::External,
    // IncomingSocSocRecovAlert31 -> AlertPeripheral::External
    AlertPeripheral::External,
    // IncomingSocSocFatalAlert0 -> AlertPeripheral::External
    AlertPeripheral::External,
    // IncomingSocSocFatalAlert1 -> AlertPeripheral::External
    AlertPeripheral::External,
    // IncomingSocSocFatalAlert2 -> AlertPeripheral::External
    AlertPeripheral::External,
    // IncomingSocSocFatalAlert3 -> AlertPeripheral::External
    AlertPeripheral::External,
    // IncomingSocSocFatalAlert4 -> AlertPeripheral::External
    AlertPeripheral::External,
    // IncomingSocSocFatalAlert5 -> AlertPeripheral::External
    AlertPeripheral::External,
    // IncomingSocSocFatalAlert6 -> AlertPeripheral::External
    AlertPeripheral::External,
    // IncomingSocSocFatalAlert7 -> AlertPeripheral::External
    AlertPeripheral::External,
];

/// Power Manager Wakeup Signals
#[derive(Copy, Clone, PartialEq, Eq)]
#[repr(u32)]
pub enum PowerManagerWakeUps {
    SocWkupReq = 0,
}

/// Reset Manager Software Controlled Resets
#[derive(Copy, Clone, PartialEq, Eq)]
#[repr(u32)]
pub enum ResetManagerSwResets {
    SocCpu = 0,
}

/// Power Manager Reset Request Signals
#[derive(Copy, Clone, PartialEq, Eq)]
#[repr(u32)]
pub enum PowerManagerResetRequests {
    SocRstReq = 0,
}

/// Clock Manager Software-Controlled ("Gated") Clocks.
///
/// The Software has full control over these clocks.
#[derive(Copy, Clone, PartialEq, Eq)]
pub enum GateableClocks {}

/// Clock Manager Software-Hinted Clocks.
///
/// The Software has partial control over these clocks. It can ask them to stop,
/// but the clock manager is in control of whether the clock actually is stopped.
#[derive(Copy, Clone, PartialEq, Eq)]
pub enum HintableClocks {}

/// MMIO Region
///
/// MMIO region excludes any memory that is separate from the module
/// configuration space, i.e. ROM, main SRAM and mailbox SoC window are excluded
/// but retention SRAM is included.
pub const TOP_PEPPERMINT_MMIO_BASE_ADDR: usize = 0x40000000;
pub const TOP_PEPPERMINT_MMIO_SIZE_BYTES: usize = 0x10000000;
