// Copyright lowRISC contributors (OpenTitan project).
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0

// This file was generated automatically.
// Please do not modify content of this file directly.
// File generated by using template: "toplevel.rs.tpl"
// To regenerate this file follow OpenTitan topgen documentations.

#![allow(dead_code)]

//! This file contains enums and consts for use within the Rust codebase.
//!
//! These definitions are for information that depends on the top-specific chip
//! configuration, which includes:
//! - Device Memory Information (for Peripherals and Memory)
//! - PLIC Interrupt ID Names and Source Mappings
//! - Alert ID Names and Source Mappings

use core::convert::TryFrom;

/// Peripheral base address for soc device on mbx0 in top peppermint.
///
/// This should be used with #mmio_region_from_addr to access the memory-mapped
/// registers associated with the peripheral (usually via a DIF).
pub const MBX0_SOC_BASE_ADDR: usize = 0x0;

/// Peripheral size for soc device on mbx0 in top peppermint.
///
/// This is the size (in bytes) of the peripheral's reserved memory area. All
/// memory-mapped registers associated with this peripheral should have an
/// address between #MBX0_SOC_BASE_ADDR and
/// `MBX0_SOC_BASE_ADDR + MBX0_SOC_SIZE_BYTES`.
pub const MBX0_SOC_SIZE_BYTES: usize = 0x20;

/// Peripheral base address for soc device on mbx1 in top peppermint.
///
/// This should be used with #mmio_region_from_addr to access the memory-mapped
/// registers associated with the peripheral (usually via a DIF).
pub const MBX1_SOC_BASE_ADDR: usize = 0x10000;

/// Peripheral size for soc device on mbx1 in top peppermint.
///
/// This is the size (in bytes) of the peripheral's reserved memory area. All
/// memory-mapped registers associated with this peripheral should have an
/// address between #MBX1_SOC_BASE_ADDR and
/// `MBX1_SOC_BASE_ADDR + MBX1_SOC_SIZE_BYTES`.
pub const MBX1_SOC_SIZE_BYTES: usize = 0x20;
