// Copyright lowRISC contributors (OpenTitan project).
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0

// This file was generated automatically.
// Please do not modify content of this file directly.
// File generated by using template: "toplevel.rs.tpl"
// To regenerate this file follow OpenTitan topgen documentations.

#![allow(dead_code)]

//! This file contains enums and consts for use within the Rust codebase.
//!
//! These definitions are for information that depends on the top-specific chip
//! configuration, which includes:
//! - Device Memory Information (for Peripherals and Memory)
//! - PLIC Interrupt ID Names and Source Mappings
//! - Alert ID Names and Source Mappings
//! - Power Manager Wakeups

use core::convert::TryFrom;

/// Peripheral base address for pwrmgr in top peppermint.
///
/// This should be used with #mmio_region_from_addr to access the memory-mapped
/// registers associated with the peripheral (usually via a DIF).
pub const PWRMGR_BASE_ADDR: usize = 0x40400000;

/// Peripheral size for pwrmgr in top peppermint.
///
/// This is the size (in bytes) of the peripheral's reserved memory area. All
/// memory-mapped registers associated with this peripheral should have an
/// address between #PWRMGR_BASE_ADDR and
/// `PWRMGR_BASE_ADDR + PWRMGR_SIZE_BYTES`.
pub const PWRMGR_SIZE_BYTES: usize = 0x80;

/// Peripheral base address for rstmgr in top peppermint.
///
/// This should be used with #mmio_region_from_addr to access the memory-mapped
/// registers associated with the peripheral (usually via a DIF).
pub const RSTMGR_BASE_ADDR: usize = 0x40410000;

/// Peripheral size for rstmgr in top peppermint.
///
/// This is the size (in bytes) of the peripheral's reserved memory area. All
/// memory-mapped registers associated with this peripheral should have an
/// address between #RSTMGR_BASE_ADDR and
/// `RSTMGR_BASE_ADDR + RSTMGR_SIZE_BYTES`.
pub const RSTMGR_SIZE_BYTES: usize = 0x40;

/// Peripheral base address for clkmgr in top peppermint.
///
/// This should be used with #mmio_region_from_addr to access the memory-mapped
/// registers associated with the peripheral (usually via a DIF).
pub const CLKMGR_BASE_ADDR: usize = 0x40420000;

/// Peripheral size for clkmgr in top peppermint.
///
/// This is the size (in bytes) of the peripheral's reserved memory area. All
/// memory-mapped registers associated with this peripheral should have an
/// address between #CLKMGR_BASE_ADDR and
/// `CLKMGR_BASE_ADDR + CLKMGR_SIZE_BYTES`.
pub const CLKMGR_SIZE_BYTES: usize = 0x40;

/// Peripheral base address for alert_handler in top peppermint.
///
/// This should be used with #mmio_region_from_addr to access the memory-mapped
/// registers associated with the peripheral (usually via a DIF).
pub const ALERT_HANDLER_BASE_ADDR: usize = 0x40450000;

/// Peripheral size for alert_handler in top peppermint.
///
/// This is the size (in bytes) of the peripheral's reserved memory area. All
/// memory-mapped registers associated with this peripheral should have an
/// address between #ALERT_HANDLER_BASE_ADDR and
/// `ALERT_HANDLER_BASE_ADDR + ALERT_HANDLER_SIZE_BYTES`.
pub const ALERT_HANDLER_SIZE_BYTES: usize = 0x800;

/// Peripheral base address for regs device on sram_ctrl_ret_aon in top peppermint.
///
/// This should be used with #mmio_region_from_addr to access the memory-mapped
/// registers associated with the peripheral (usually via a DIF).
pub const SRAM_CTRL_RET_AON_REGS_BASE_ADDR: usize = 0x40460000;

/// Peripheral size for regs device on sram_ctrl_ret_aon in top peppermint.
///
/// This is the size (in bytes) of the peripheral's reserved memory area. All
/// memory-mapped registers associated with this peripheral should have an
/// address between #SRAM_CTRL_RET_AON_REGS_BASE_ADDR and
/// `SRAM_CTRL_RET_AON_REGS_BASE_ADDR + SRAM_CTRL_RET_AON_REGS_SIZE_BYTES`.
pub const SRAM_CTRL_RET_AON_REGS_SIZE_BYTES: usize = 0x40;

/// Peripheral base address for core device on otp_ctrl in top peppermint.
///
/// This should be used with #mmio_region_from_addr to access the memory-mapped
/// registers associated with the peripheral (usually via a DIF).
pub const OTP_CTRL_CORE_BASE_ADDR: usize = 0x30130000;

/// Peripheral size for core device on otp_ctrl in top peppermint.
///
/// This is the size (in bytes) of the peripheral's reserved memory area. All
/// memory-mapped registers associated with this peripheral should have an
/// address between #OTP_CTRL_CORE_BASE_ADDR and
/// `OTP_CTRL_CORE_BASE_ADDR + OTP_CTRL_CORE_SIZE_BYTES`.
pub const OTP_CTRL_CORE_SIZE_BYTES: usize = 0x4000;

/// Peripheral base address for prim device on otp_macro in top peppermint.
///
/// This should be used with #mmio_region_from_addr to access the memory-mapped
/// registers associated with the peripheral (usually via a DIF).
pub const OTP_MACRO_PRIM_BASE_ADDR: usize = 0x30140000;

/// Peripheral size for prim device on otp_macro in top peppermint.
///
/// This is the size (in bytes) of the peripheral's reserved memory area. All
/// memory-mapped registers associated with this peripheral should have an
/// address between #OTP_MACRO_PRIM_BASE_ADDR and
/// `OTP_MACRO_PRIM_BASE_ADDR + OTP_MACRO_PRIM_SIZE_BYTES`.
pub const OTP_MACRO_PRIM_SIZE_BYTES: usize = 0x20;

/// Peripheral base address for regs device on lc_ctrl in top peppermint.
///
/// This should be used with #mmio_region_from_addr to access the memory-mapped
/// registers associated with the peripheral (usually via a DIF).
pub const LC_CTRL_REGS_BASE_ADDR: usize = 0x30150000;

/// Peripheral size for regs device on lc_ctrl in top peppermint.
///
/// This is the size (in bytes) of the peripheral's reserved memory area. All
/// memory-mapped registers associated with this peripheral should have an
/// address between #LC_CTRL_REGS_BASE_ADDR and
/// `LC_CTRL_REGS_BASE_ADDR + LC_CTRL_REGS_SIZE_BYTES`.
pub const LC_CTRL_REGS_SIZE_BYTES: usize = 0x100;

/// Peripheral base address for regs device on rv_dm in top peppermint.
///
/// This should be used with #mmio_region_from_addr to access the memory-mapped
/// registers associated with the peripheral (usually via a DIF).
pub const RV_DM_REGS_BASE_ADDR: usize = 0x21200000;

/// Peripheral size for regs device on rv_dm in top peppermint.
///
/// This is the size (in bytes) of the peripheral's reserved memory area. All
/// memory-mapped registers associated with this peripheral should have an
/// address between #RV_DM_REGS_BASE_ADDR and
/// `RV_DM_REGS_BASE_ADDR + RV_DM_REGS_SIZE_BYTES`.
pub const RV_DM_REGS_SIZE_BYTES: usize = 0x10;

/// Peripheral base address for mem device on rv_dm in top peppermint.
///
/// This should be used with #mmio_region_from_addr to access the memory-mapped
/// registers associated with the peripheral (usually via a DIF).
pub const RV_DM_MEM_BASE_ADDR: usize = 0x50000;

/// Peripheral size for mem device on rv_dm in top peppermint.
///
/// This is the size (in bytes) of the peripheral's reserved memory area. All
/// memory-mapped registers associated with this peripheral should have an
/// address between #RV_DM_MEM_BASE_ADDR and
/// `RV_DM_MEM_BASE_ADDR + RV_DM_MEM_SIZE_BYTES`.
pub const RV_DM_MEM_SIZE_BYTES: usize = 0x1000;

/// Peripheral base address for rv_plic in top peppermint.
///
/// This should be used with #mmio_region_from_addr to access the memory-mapped
/// registers associated with the peripheral (usually via a DIF).
pub const RV_PLIC_BASE_ADDR: usize = 0x28000000;

/// Peripheral size for rv_plic in top peppermint.
///
/// This is the size (in bytes) of the peripheral's reserved memory area. All
/// memory-mapped registers associated with this peripheral should have an
/// address between #RV_PLIC_BASE_ADDR and
/// `RV_PLIC_BASE_ADDR + RV_PLIC_SIZE_BYTES`.
pub const RV_PLIC_SIZE_BYTES: usize = 0x8000000;

/// Peripheral base address for rv_timer in top peppermint.
///
/// This should be used with #mmio_region_from_addr to access the memory-mapped
/// registers associated with the peripheral (usually via a DIF).
pub const RV_TIMER_BASE_ADDR: usize = 0x21190000;

/// Peripheral size for rv_timer in top peppermint.
///
/// This is the size (in bytes) of the peripheral's reserved memory area. All
/// memory-mapped registers associated with this peripheral should have an
/// address between #RV_TIMER_BASE_ADDR and
/// `RV_TIMER_BASE_ADDR + RV_TIMER_SIZE_BYTES`.
pub const RV_TIMER_SIZE_BYTES: usize = 0x200;

/// Peripheral base address for aes in top peppermint.
///
/// This should be used with #mmio_region_from_addr to access the memory-mapped
/// registers associated with the peripheral (usually via a DIF).
pub const AES_BASE_ADDR: usize = 0x21100000;

/// Peripheral size for aes in top peppermint.
///
/// This is the size (in bytes) of the peripheral's reserved memory area. All
/// memory-mapped registers associated with this peripheral should have an
/// address between #AES_BASE_ADDR and
/// `AES_BASE_ADDR + AES_SIZE_BYTES`.
pub const AES_SIZE_BYTES: usize = 0x100;

/// Peripheral base address for hmac in top peppermint.
///
/// This should be used with #mmio_region_from_addr to access the memory-mapped
/// registers associated with the peripheral (usually via a DIF).
pub const HMAC_BASE_ADDR: usize = 0x21110000;

/// Peripheral size for hmac in top peppermint.
///
/// This is the size (in bytes) of the peripheral's reserved memory area. All
/// memory-mapped registers associated with this peripheral should have an
/// address between #HMAC_BASE_ADDR and
/// `HMAC_BASE_ADDR + HMAC_SIZE_BYTES`.
pub const HMAC_SIZE_BYTES: usize = 0x2000;

/// Peripheral base address for kmac in top peppermint.
///
/// This should be used with #mmio_region_from_addr to access the memory-mapped
/// registers associated with the peripheral (usually via a DIF).
pub const KMAC_BASE_ADDR: usize = 0x21120000;

/// Peripheral size for kmac in top peppermint.
///
/// This is the size (in bytes) of the peripheral's reserved memory area. All
/// memory-mapped registers associated with this peripheral should have an
/// address between #KMAC_BASE_ADDR and
/// `KMAC_BASE_ADDR + KMAC_SIZE_BYTES`.
pub const KMAC_SIZE_BYTES: usize = 0x1000;

/// Peripheral base address for otbn in top peppermint.
///
/// This should be used with #mmio_region_from_addr to access the memory-mapped
/// registers associated with the peripheral (usually via a DIF).
pub const OTBN_BASE_ADDR: usize = 0x21130000;

/// Peripheral size for otbn in top peppermint.
///
/// This is the size (in bytes) of the peripheral's reserved memory area. All
/// memory-mapped registers associated with this peripheral should have an
/// address between #OTBN_BASE_ADDR and
/// `OTBN_BASE_ADDR + OTBN_SIZE_BYTES`.
pub const OTBN_SIZE_BYTES: usize = 0x10000;

/// Peripheral base address for keymgr_dpe in top peppermint.
///
/// This should be used with #mmio_region_from_addr to access the memory-mapped
/// registers associated with the peripheral (usually via a DIF).
pub const KEYMGR_DPE_BASE_ADDR: usize = 0x21140000;

/// Peripheral size for keymgr_dpe in top peppermint.
///
/// This is the size (in bytes) of the peripheral's reserved memory area. All
/// memory-mapped registers associated with this peripheral should have an
/// address between #KEYMGR_DPE_BASE_ADDR and
/// `KEYMGR_DPE_BASE_ADDR + KEYMGR_DPE_SIZE_BYTES`.
pub const KEYMGR_DPE_SIZE_BYTES: usize = 0x100;

/// Peripheral base address for csrng in top peppermint.
///
/// This should be used with #mmio_region_from_addr to access the memory-mapped
/// registers associated with the peripheral (usually via a DIF).
pub const CSRNG_BASE_ADDR: usize = 0x21150000;

/// Peripheral size for csrng in top peppermint.
///
/// This is the size (in bytes) of the peripheral's reserved memory area. All
/// memory-mapped registers associated with this peripheral should have an
/// address between #CSRNG_BASE_ADDR and
/// `CSRNG_BASE_ADDR + CSRNG_SIZE_BYTES`.
pub const CSRNG_SIZE_BYTES: usize = 0x80;

/// Peripheral base address for entropy_src in top peppermint.
///
/// This should be used with #mmio_region_from_addr to access the memory-mapped
/// registers associated with the peripheral (usually via a DIF).
pub const ENTROPY_SRC_BASE_ADDR: usize = 0x21160000;

/// Peripheral size for entropy_src in top peppermint.
///
/// This is the size (in bytes) of the peripheral's reserved memory area. All
/// memory-mapped registers associated with this peripheral should have an
/// address between #ENTROPY_SRC_BASE_ADDR and
/// `ENTROPY_SRC_BASE_ADDR + ENTROPY_SRC_SIZE_BYTES`.
pub const ENTROPY_SRC_SIZE_BYTES: usize = 0x100;

/// Peripheral base address for edn0 in top peppermint.
///
/// This should be used with #mmio_region_from_addr to access the memory-mapped
/// registers associated with the peripheral (usually via a DIF).
pub const EDN0_BASE_ADDR: usize = 0x21170000;

/// Peripheral size for edn0 in top peppermint.
///
/// This is the size (in bytes) of the peripheral's reserved memory area. All
/// memory-mapped registers associated with this peripheral should have an
/// address between #EDN0_BASE_ADDR and
/// `EDN0_BASE_ADDR + EDN0_SIZE_BYTES`.
pub const EDN0_SIZE_BYTES: usize = 0x80;

/// Peripheral base address for edn1 in top peppermint.
///
/// This should be used with #mmio_region_from_addr to access the memory-mapped
/// registers associated with the peripheral (usually via a DIF).
pub const EDN1_BASE_ADDR: usize = 0x21180000;

/// Peripheral size for edn1 in top peppermint.
///
/// This is the size (in bytes) of the peripheral's reserved memory area. All
/// memory-mapped registers associated with this peripheral should have an
/// address between #EDN1_BASE_ADDR and
/// `EDN1_BASE_ADDR + EDN1_SIZE_BYTES`.
pub const EDN1_SIZE_BYTES: usize = 0x80;

/// Peripheral base address for regs device on sram_ctrl_main in top peppermint.
///
/// This should be used with #mmio_region_from_addr to access the memory-mapped
/// registers associated with the peripheral (usually via a DIF).
pub const SRAM_CTRL_MAIN_REGS_BASE_ADDR: usize = 0x211C0000;

/// Peripheral size for regs device on sram_ctrl_main in top peppermint.
///
/// This is the size (in bytes) of the peripheral's reserved memory area. All
/// memory-mapped registers associated with this peripheral should have an
/// address between #SRAM_CTRL_MAIN_REGS_BASE_ADDR and
/// `SRAM_CTRL_MAIN_REGS_BASE_ADDR + SRAM_CTRL_MAIN_REGS_SIZE_BYTES`.
pub const SRAM_CTRL_MAIN_REGS_SIZE_BYTES: usize = 0x40;

/// Peripheral base address for regs device on rom_ctrl in top peppermint.
///
/// This should be used with #mmio_region_from_addr to access the memory-mapped
/// registers associated with the peripheral (usually via a DIF).
pub const ROM_CTRL_REGS_BASE_ADDR: usize = 0x211E0000;

/// Peripheral size for regs device on rom_ctrl in top peppermint.
///
/// This is the size (in bytes) of the peripheral's reserved memory area. All
/// memory-mapped registers associated with this peripheral should have an
/// address between #ROM_CTRL_REGS_BASE_ADDR and
/// `ROM_CTRL_REGS_BASE_ADDR + ROM_CTRL_REGS_SIZE_BYTES`.
pub const ROM_CTRL_REGS_SIZE_BYTES: usize = 0x80;

/// Peripheral base address for dma in top peppermint.
///
/// This should be used with #mmio_region_from_addr to access the memory-mapped
/// registers associated with the peripheral (usually via a DIF).
pub const DMA_BASE_ADDR: usize = 0x22010000;

/// Peripheral size for dma in top peppermint.
///
/// This is the size (in bytes) of the peripheral's reserved memory area. All
/// memory-mapped registers associated with this peripheral should have an
/// address between #DMA_BASE_ADDR and
/// `DMA_BASE_ADDR + DMA_SIZE_BYTES`.
pub const DMA_SIZE_BYTES: usize = 0x200;

/// Peripheral base address for core device on mbx0 in top peppermint.
///
/// This should be used with #mmio_region_from_addr to access the memory-mapped
/// registers associated with the peripheral (usually via a DIF).
pub const MBX0_CORE_BASE_ADDR: usize = 0x22000000;

/// Peripheral size for core device on mbx0 in top peppermint.
///
/// This is the size (in bytes) of the peripheral's reserved memory area. All
/// memory-mapped registers associated with this peripheral should have an
/// address between #MBX0_CORE_BASE_ADDR and
/// `MBX0_CORE_BASE_ADDR + MBX0_CORE_SIZE_BYTES`.
pub const MBX0_CORE_SIZE_BYTES: usize = 0x80;

/// Peripheral base address for core device on mbx1 in top peppermint.
///
/// This should be used with #mmio_region_from_addr to access the memory-mapped
/// registers associated with the peripheral (usually via a DIF).
pub const MBX1_CORE_BASE_ADDR: usize = 0x22000100;

/// Peripheral size for core device on mbx1 in top peppermint.
///
/// This is the size (in bytes) of the peripheral's reserved memory area. All
/// memory-mapped registers associated with this peripheral should have an
/// address between #MBX1_CORE_BASE_ADDR and
/// `MBX1_CORE_BASE_ADDR + MBX1_CORE_SIZE_BYTES`.
pub const MBX1_CORE_SIZE_BYTES: usize = 0x80;

/// Peripheral base address for cfg device on rv_core_ibex in top peppermint.
///
/// This should be used with #mmio_region_from_addr to access the memory-mapped
/// registers associated with the peripheral (usually via a DIF).
pub const RV_CORE_IBEX_CFG_BASE_ADDR: usize = 0x211F0000;

/// Peripheral size for cfg device on rv_core_ibex in top peppermint.
///
/// This is the size (in bytes) of the peripheral's reserved memory area. All
/// memory-mapped registers associated with this peripheral should have an
/// address between #RV_CORE_IBEX_CFG_BASE_ADDR and
/// `RV_CORE_IBEX_CFG_BASE_ADDR + RV_CORE_IBEX_CFG_SIZE_BYTES`.
pub const RV_CORE_IBEX_CFG_SIZE_BYTES: usize = 0x800;

/// Memory base address for ram memory on sram_ctrl_ret_aon in top peppermint.
pub const SRAM_CTRL_RET_AON_RAM_BASE_ADDR: usize = 0x40470000;

/// Memory size for ram memory on sram_ctrl_ret_aon in top peppermint.
pub const SRAM_CTRL_RET_AON_RAM_SIZE_BYTES: usize = 0x2000;

/// Memory base address for ram memory on sram_ctrl_main in top peppermint.
pub const SRAM_CTRL_MAIN_RAM_BASE_ADDR: usize = 0x10000000;

/// Memory size for ram memory on sram_ctrl_main in top peppermint.
pub const SRAM_CTRL_MAIN_RAM_SIZE_BYTES: usize = 0x30000;

/// Memory base address for rom memory on rom_ctrl in top peppermint.
pub const ROM_CTRL_ROM_BASE_ADDR: usize = 0x20000;

/// Memory size for rom memory on rom_ctrl in top peppermint.
pub const ROM_CTRL_ROM_SIZE_BYTES: usize = 0x20000;

/// Memory base address for ctn memory on ahb_bridge in top peppermint.
pub const AHB_BRIDGE_CTN_BASE_ADDR: usize = 0x80000000;

/// Memory size for ctn memory on ahb_bridge in top peppermint.
pub const AHB_BRIDGE_CTN_SIZE_BYTES: usize = 0x10000000;

/// PLIC Interrupt Source Peripheral.
///
/// Enumeration used to determine which peripheral asserted the corresponding
/// interrupt.
#[derive(Copy, Clone, PartialEq, Eq)]
#[repr(u32)]
pub enum PlicPeripheral {
    /// Unknown Peripheral
    Unknown = 0,
    /// pwrmgr
    Pwrmgr = 1,
    /// alert_handler
    AlertHandler = 2,
    /// otp_ctrl
    OtpCtrl = 3,
    /// rv_timer
    RvTimer = 4,
    /// hmac
    Hmac = 5,
    /// kmac
    Kmac = 6,
    /// otbn
    Otbn = 7,
    /// keymgr_dpe
    KeymgrDpe = 8,
    /// csrng
    Csrng = 9,
    /// entropy_src
    EntropySrc = 10,
    /// edn0
    Edn0 = 11,
    /// edn1
    Edn1 = 12,
    /// dma
    Dma = 13,
    /// mbx0
    Mbx0 = 14,
    /// mbx1
    Mbx1 = 15,
}

impl TryFrom<u32> for PlicPeripheral {
    type Error = u32;
    fn try_from(val: u32) -> Result<Self, Self::Error> {
        match val {
            0 => Ok(Self::Unknown),
            1 => Ok(Self::Pwrmgr),
            2 => Ok(Self::AlertHandler),
            3 => Ok(Self::OtpCtrl),
            4 => Ok(Self::RvTimer),
            5 => Ok(Self::Hmac),
            6 => Ok(Self::Kmac),
            7 => Ok(Self::Otbn),
            8 => Ok(Self::KeymgrDpe),
            9 => Ok(Self::Csrng),
            10 => Ok(Self::EntropySrc),
            11 => Ok(Self::Edn0),
            12 => Ok(Self::Edn1),
            13 => Ok(Self::Dma),
            14 => Ok(Self::Mbx0),
            15 => Ok(Self::Mbx1),
            _ => Err(val),
        }
    }
}

/// PLIC Interrupt Source.
///
/// Enumeration of all PLIC interrupt sources. The interrupt sources belonging to
/// the same peripheral are guaranteed to be consecutive.
#[derive(Copy, Clone, PartialEq, Eq)]
#[repr(u32)]
pub enum PlicIrqId {
    /// No Interrupt
    None = 0,
    /// pwrmgr_wakeup
    PwrmgrWakeup = 1,
    /// alert_handler_classa
    AlertHandlerClassa = 2,
    /// alert_handler_classb
    AlertHandlerClassb = 3,
    /// alert_handler_classc
    AlertHandlerClassc = 4,
    /// alert_handler_classd
    AlertHandlerClassd = 5,
    /// otp_ctrl_otp_operation_done
    OtpCtrlOtpOperationDone = 6,
    /// otp_ctrl_otp_error
    OtpCtrlOtpError = 7,
    /// rv_timer_timer_expired_hart0_timer0
    RvTimerTimerExpiredHart0Timer0 = 8,
    /// hmac_hmac_done
    HmacHmacDone = 9,
    /// hmac_fifo_empty
    HmacFifoEmpty = 10,
    /// hmac_hmac_err
    HmacHmacErr = 11,
    /// kmac_kmac_done
    KmacKmacDone = 12,
    /// kmac_fifo_empty
    KmacFifoEmpty = 13,
    /// kmac_kmac_err
    KmacKmacErr = 14,
    /// otbn_done
    OtbnDone = 15,
    /// keymgr_dpe_op_done
    KeymgrDpeOpDone = 16,
    /// csrng_cs_cmd_req_done
    CsrngCsCmdReqDone = 17,
    /// csrng_cs_entropy_req
    CsrngCsEntropyReq = 18,
    /// csrng_cs_hw_inst_exc
    CsrngCsHwInstExc = 19,
    /// csrng_cs_fatal_err
    CsrngCsFatalErr = 20,
    /// entropy_src_es_entropy_valid
    EntropySrcEsEntropyValid = 21,
    /// entropy_src_es_health_test_failed
    EntropySrcEsHealthTestFailed = 22,
    /// entropy_src_es_observe_fifo_ready
    EntropySrcEsObserveFifoReady = 23,
    /// entropy_src_es_fatal_err
    EntropySrcEsFatalErr = 24,
    /// edn0_edn_cmd_req_done
    Edn0EdnCmdReqDone = 25,
    /// edn0_edn_fatal_err
    Edn0EdnFatalErr = 26,
    /// edn1_edn_cmd_req_done
    Edn1EdnCmdReqDone = 27,
    /// edn1_edn_fatal_err
    Edn1EdnFatalErr = 28,
    /// dma_dma_done
    DmaDmaDone = 29,
    /// dma_dma_chunk_done
    DmaDmaChunkDone = 30,
    /// dma_dma_error
    DmaDmaError = 31,
    /// mbx0_mbx_ready
    Mbx0MbxReady = 32,
    /// mbx0_mbx_abort
    Mbx0MbxAbort = 33,
    /// mbx0_mbx_error
    Mbx0MbxError = 34,
    /// mbx1_mbx_ready
    Mbx1MbxReady = 35,
    /// mbx1_mbx_abort
    Mbx1MbxAbort = 36,
    /// mbx1_mbx_error
    Mbx1MbxError = 37,
    /// soc_irq_0
    SocIrq0 = 38,
    /// soc_irq_1
    SocIrq1 = 39,
    /// soc_irq_2
    SocIrq2 = 40,
    /// soc_irq_3
    SocIrq3 = 41,
}

impl TryFrom<u32> for PlicIrqId {
    type Error = u32;
    fn try_from(val: u32) -> Result<Self, Self::Error> {
        match val {
            0 => Ok(Self::None),
            1 => Ok(Self::PwrmgrWakeup),
            2 => Ok(Self::AlertHandlerClassa),
            3 => Ok(Self::AlertHandlerClassb),
            4 => Ok(Self::AlertHandlerClassc),
            5 => Ok(Self::AlertHandlerClassd),
            6 => Ok(Self::OtpCtrlOtpOperationDone),
            7 => Ok(Self::OtpCtrlOtpError),
            8 => Ok(Self::RvTimerTimerExpiredHart0Timer0),
            9 => Ok(Self::HmacHmacDone),
            10 => Ok(Self::HmacFifoEmpty),
            11 => Ok(Self::HmacHmacErr),
            12 => Ok(Self::KmacKmacDone),
            13 => Ok(Self::KmacFifoEmpty),
            14 => Ok(Self::KmacKmacErr),
            15 => Ok(Self::OtbnDone),
            16 => Ok(Self::KeymgrDpeOpDone),
            17 => Ok(Self::CsrngCsCmdReqDone),
            18 => Ok(Self::CsrngCsEntropyReq),
            19 => Ok(Self::CsrngCsHwInstExc),
            20 => Ok(Self::CsrngCsFatalErr),
            21 => Ok(Self::EntropySrcEsEntropyValid),
            22 => Ok(Self::EntropySrcEsHealthTestFailed),
            23 => Ok(Self::EntropySrcEsObserveFifoReady),
            24 => Ok(Self::EntropySrcEsFatalErr),
            25 => Ok(Self::Edn0EdnCmdReqDone),
            26 => Ok(Self::Edn0EdnFatalErr),
            27 => Ok(Self::Edn1EdnCmdReqDone),
            28 => Ok(Self::Edn1EdnFatalErr),
            29 => Ok(Self::DmaDmaDone),
            30 => Ok(Self::DmaDmaChunkDone),
            31 => Ok(Self::DmaDmaError),
            32 => Ok(Self::Mbx0MbxReady),
            33 => Ok(Self::Mbx0MbxAbort),
            34 => Ok(Self::Mbx0MbxError),
            35 => Ok(Self::Mbx1MbxReady),
            36 => Ok(Self::Mbx1MbxAbort),
            37 => Ok(Self::Mbx1MbxError),
            38 => Ok(Self::SocIrq0),
            39 => Ok(Self::SocIrq1),
            40 => Ok(Self::SocIrq2),
            41 => Ok(Self::SocIrq3),
            _ => Err(val),
        }
    }
}

/// PLIC Interrupt Target.
///
/// Enumeration used to determine which set of IE, CC, threshold registers to
/// access for a given interrupt target.
#[derive(Copy, Clone, PartialEq, Eq)]
#[repr(u32)]
pub enum PlicTarget {
    /// Ibex Core 0
    Ibex0 = 0,
}

/// PLIC Interrupt Source to Peripheral Map
///
/// This array is a mapping from `PlicIrqId` to
/// `PlicPeripheral`.
pub const PLIC_INTERRUPT_FOR_PERIPHERAL: [PlicPeripheral; 42] = [
    // None -> PlicPeripheral::Unknown
    PlicPeripheral::Unknown,
    // PwrmgrWakeup -> PlicPeripheral::Pwrmgr
    PlicPeripheral::Pwrmgr,
    // AlertHandlerClassa -> PlicPeripheral::AlertHandler
    PlicPeripheral::AlertHandler,
    // AlertHandlerClassb -> PlicPeripheral::AlertHandler
    PlicPeripheral::AlertHandler,
    // AlertHandlerClassc -> PlicPeripheral::AlertHandler
    PlicPeripheral::AlertHandler,
    // AlertHandlerClassd -> PlicPeripheral::AlertHandler
    PlicPeripheral::AlertHandler,
    // OtpCtrlOtpOperationDone -> PlicPeripheral::OtpCtrl
    PlicPeripheral::OtpCtrl,
    // OtpCtrlOtpError -> PlicPeripheral::OtpCtrl
    PlicPeripheral::OtpCtrl,
    // RvTimerTimerExpiredHart0Timer0 -> PlicPeripheral::RvTimer
    PlicPeripheral::RvTimer,
    // HmacHmacDone -> PlicPeripheral::Hmac
    PlicPeripheral::Hmac,
    // HmacFifoEmpty -> PlicPeripheral::Hmac
    PlicPeripheral::Hmac,
    // HmacHmacErr -> PlicPeripheral::Hmac
    PlicPeripheral::Hmac,
    // KmacKmacDone -> PlicPeripheral::Kmac
    PlicPeripheral::Kmac,
    // KmacFifoEmpty -> PlicPeripheral::Kmac
    PlicPeripheral::Kmac,
    // KmacKmacErr -> PlicPeripheral::Kmac
    PlicPeripheral::Kmac,
    // OtbnDone -> PlicPeripheral::Otbn
    PlicPeripheral::Otbn,
    // KeymgrDpeOpDone -> PlicPeripheral::KeymgrDpe
    PlicPeripheral::KeymgrDpe,
    // CsrngCsCmdReqDone -> PlicPeripheral::Csrng
    PlicPeripheral::Csrng,
    // CsrngCsEntropyReq -> PlicPeripheral::Csrng
    PlicPeripheral::Csrng,
    // CsrngCsHwInstExc -> PlicPeripheral::Csrng
    PlicPeripheral::Csrng,
    // CsrngCsFatalErr -> PlicPeripheral::Csrng
    PlicPeripheral::Csrng,
    // EntropySrcEsEntropyValid -> PlicPeripheral::EntropySrc
    PlicPeripheral::EntropySrc,
    // EntropySrcEsHealthTestFailed -> PlicPeripheral::EntropySrc
    PlicPeripheral::EntropySrc,
    // EntropySrcEsObserveFifoReady -> PlicPeripheral::EntropySrc
    PlicPeripheral::EntropySrc,
    // EntropySrcEsFatalErr -> PlicPeripheral::EntropySrc
    PlicPeripheral::EntropySrc,
    // Edn0EdnCmdReqDone -> PlicPeripheral::Edn0
    PlicPeripheral::Edn0,
    // Edn0EdnFatalErr -> PlicPeripheral::Edn0
    PlicPeripheral::Edn0,
    // Edn1EdnCmdReqDone -> PlicPeripheral::Edn1
    PlicPeripheral::Edn1,
    // Edn1EdnFatalErr -> PlicPeripheral::Edn1
    PlicPeripheral::Edn1,
    // DmaDmaDone -> PlicPeripheral::Dma
    PlicPeripheral::Dma,
    // DmaDmaChunkDone -> PlicPeripheral::Dma
    PlicPeripheral::Dma,
    // DmaDmaError -> PlicPeripheral::Dma
    PlicPeripheral::Dma,
    // Mbx0MbxReady -> PlicPeripheral::Mbx0
    PlicPeripheral::Mbx0,
    // Mbx0MbxAbort -> PlicPeripheral::Mbx0
    PlicPeripheral::Mbx0,
    // Mbx0MbxError -> PlicPeripheral::Mbx0
    PlicPeripheral::Mbx0,
    // Mbx1MbxReady -> PlicPeripheral::Mbx1
    PlicPeripheral::Mbx1,
    // Mbx1MbxAbort -> PlicPeripheral::Mbx1
    PlicPeripheral::Mbx1,
    // Mbx1MbxError -> PlicPeripheral::Mbx1
    PlicPeripheral::Mbx1,
    // SocIrq0 -> PlicPeripheral::Unknown
    PlicPeripheral::Unknown,
    // SocIrq1 -> PlicPeripheral::Unknown
    PlicPeripheral::Unknown,
    // SocIrq2 -> PlicPeripheral::Unknown
    PlicPeripheral::Unknown,
    // SocIrq3 -> PlicPeripheral::Unknown
    PlicPeripheral::Unknown,
];

/// Alert Handler Source Peripheral.
///
/// Enumeration used to determine which peripheral asserted the corresponding
/// alert.
#[derive(Copy, Clone, PartialEq, Eq)]
#[repr(u32)]
pub enum AlertPeripheral {
    /// External Peripheral
    External = 0,
    /// pwrmgr
    Pwrmgr = 1,
    /// rstmgr
    Rstmgr = 2,
    /// clkmgr
    Clkmgr = 3,
    /// sram_ctrl_ret_aon
    SramCtrlRetAon = 4,
    /// otp_ctrl
    OtpCtrl = 5,
    /// lc_ctrl
    LcCtrl = 6,
    /// rv_dm
    RvDm = 7,
    /// rv_plic
    RvPlic = 8,
    /// rv_timer
    RvTimer = 9,
    /// aes
    Aes = 10,
    /// hmac
    Hmac = 11,
    /// kmac
    Kmac = 12,
    /// otbn
    Otbn = 13,
    /// keymgr_dpe
    KeymgrDpe = 14,
    /// csrng
    Csrng = 15,
    /// entropy_src
    EntropySrc = 16,
    /// edn0
    Edn0 = 17,
    /// edn1
    Edn1 = 18,
    /// sram_ctrl_main
    SramCtrlMain = 19,
    /// rom_ctrl
    RomCtrl = 20,
    /// dma
    Dma = 21,
    /// mbx0
    Mbx0 = 22,
    /// mbx1
    Mbx1 = 23,
    /// rv_core_ibex
    RvCoreIbex = 24,
}

/// Alert Handler Alert Source.
///
/// Enumeration of all Alert Handler Alert Sources. The alert sources belonging to
/// the same peripheral are guaranteed to be consecutive.
#[derive(Copy, Clone, PartialEq, Eq)]
#[repr(u32)]
pub enum AlertId {
    /// pwrmgr_fatal_fault
    PwrmgrFatalFault = 0,
    /// rstmgr_fatal_fault
    RstmgrFatalFault = 1,
    /// rstmgr_fatal_cnsty_fault
    RstmgrFatalCnstyFault = 2,
    /// clkmgr_recov_fault
    ClkmgrRecovFault = 3,
    /// clkmgr_fatal_fault
    ClkmgrFatalFault = 4,
    /// sram_ctrl_ret_aon_fatal_error
    SramCtrlRetAonFatalError = 5,
    /// otp_ctrl_fatal_macro_error
    OtpCtrlFatalMacroError = 6,
    /// otp_ctrl_fatal_check_error
    OtpCtrlFatalCheckError = 7,
    /// otp_ctrl_fatal_bus_integ_error
    OtpCtrlFatalBusIntegError = 8,
    /// otp_ctrl_fatal_prim_otp_alert
    OtpCtrlFatalPrimOtpAlert = 9,
    /// otp_ctrl_recov_prim_otp_alert
    OtpCtrlRecovPrimOtpAlert = 10,
    /// lc_ctrl_fatal_prog_error
    LcCtrlFatalProgError = 11,
    /// lc_ctrl_fatal_state_error
    LcCtrlFatalStateError = 12,
    /// lc_ctrl_fatal_bus_integ_error
    LcCtrlFatalBusIntegError = 13,
    /// rv_dm_fatal_fault
    RvDmFatalFault = 14,
    /// rv_plic_fatal_fault
    RvPlicFatalFault = 15,
    /// rv_timer_fatal_fault
    RvTimerFatalFault = 16,
    /// aes_recov_ctrl_update_err
    AesRecovCtrlUpdateErr = 17,
    /// aes_fatal_fault
    AesFatalFault = 18,
    /// hmac_fatal_fault
    HmacFatalFault = 19,
    /// kmac_recov_operation_err
    KmacRecovOperationErr = 20,
    /// kmac_fatal_fault_err
    KmacFatalFaultErr = 21,
    /// otbn_fatal
    OtbnFatal = 22,
    /// otbn_recov
    OtbnRecov = 23,
    /// keymgr_dpe_recov_operation_err
    KeymgrDpeRecovOperationErr = 24,
    /// keymgr_dpe_fatal_fault_err
    KeymgrDpeFatalFaultErr = 25,
    /// csrng_recov_alert
    CsrngRecovAlert = 26,
    /// csrng_fatal_alert
    CsrngFatalAlert = 27,
    /// entropy_src_recov_alert
    EntropySrcRecovAlert = 28,
    /// entropy_src_fatal_alert
    EntropySrcFatalAlert = 29,
    /// edn0_recov_alert
    Edn0RecovAlert = 30,
    /// edn0_fatal_alert
    Edn0FatalAlert = 31,
    /// edn1_recov_alert
    Edn1RecovAlert = 32,
    /// edn1_fatal_alert
    Edn1FatalAlert = 33,
    /// sram_ctrl_main_fatal_error
    SramCtrlMainFatalError = 34,
    /// rom_ctrl_fatal
    RomCtrlFatal = 35,
    /// dma_fatal_fault
    DmaFatalFault = 36,
    /// mbx0_fatal_fault
    Mbx0FatalFault = 37,
    /// mbx0_recov_fault
    Mbx0RecovFault = 38,
    /// mbx1_fatal_fault
    Mbx1FatalFault = 39,
    /// mbx1_recov_fault
    Mbx1RecovFault = 40,
    /// rv_core_ibex_fatal_sw_err
    RvCoreIbexFatalSwErr = 41,
    /// rv_core_ibex_recov_sw_err
    RvCoreIbexRecovSwErr = 42,
    /// rv_core_ibex_fatal_hw_err
    RvCoreIbexFatalHwErr = 43,
    /// rv_core_ibex_recov_hw_err
    RvCoreIbexRecovHwErr = 44,
    /// incoming_soc_soc_fatal_alert_0
    IncomingSocSocFatalAlert0 = 45,
    /// incoming_soc_soc_fatal_alert_1
    IncomingSocSocFatalAlert1 = 46,
    /// incoming_soc_soc_fatal_alert_2
    IncomingSocSocFatalAlert2 = 47,
    /// incoming_soc_soc_fatal_alert_3
    IncomingSocSocFatalAlert3 = 48,
}

impl TryFrom<u32> for AlertId {
    type Error = u32;
    fn try_from(val: u32) -> Result<Self, Self::Error> {
        match val {
            0 => Ok(Self::PwrmgrFatalFault),
            1 => Ok(Self::RstmgrFatalFault),
            2 => Ok(Self::RstmgrFatalCnstyFault),
            3 => Ok(Self::ClkmgrRecovFault),
            4 => Ok(Self::ClkmgrFatalFault),
            5 => Ok(Self::SramCtrlRetAonFatalError),
            6 => Ok(Self::OtpCtrlFatalMacroError),
            7 => Ok(Self::OtpCtrlFatalCheckError),
            8 => Ok(Self::OtpCtrlFatalBusIntegError),
            9 => Ok(Self::OtpCtrlFatalPrimOtpAlert),
            10 => Ok(Self::OtpCtrlRecovPrimOtpAlert),
            11 => Ok(Self::LcCtrlFatalProgError),
            12 => Ok(Self::LcCtrlFatalStateError),
            13 => Ok(Self::LcCtrlFatalBusIntegError),
            14 => Ok(Self::RvDmFatalFault),
            15 => Ok(Self::RvPlicFatalFault),
            16 => Ok(Self::RvTimerFatalFault),
            17 => Ok(Self::AesRecovCtrlUpdateErr),
            18 => Ok(Self::AesFatalFault),
            19 => Ok(Self::HmacFatalFault),
            20 => Ok(Self::KmacRecovOperationErr),
            21 => Ok(Self::KmacFatalFaultErr),
            22 => Ok(Self::OtbnFatal),
            23 => Ok(Self::OtbnRecov),
            24 => Ok(Self::KeymgrDpeRecovOperationErr),
            25 => Ok(Self::KeymgrDpeFatalFaultErr),
            26 => Ok(Self::CsrngRecovAlert),
            27 => Ok(Self::CsrngFatalAlert),
            28 => Ok(Self::EntropySrcRecovAlert),
            29 => Ok(Self::EntropySrcFatalAlert),
            30 => Ok(Self::Edn0RecovAlert),
            31 => Ok(Self::Edn0FatalAlert),
            32 => Ok(Self::Edn1RecovAlert),
            33 => Ok(Self::Edn1FatalAlert),
            34 => Ok(Self::SramCtrlMainFatalError),
            35 => Ok(Self::RomCtrlFatal),
            36 => Ok(Self::DmaFatalFault),
            37 => Ok(Self::Mbx0FatalFault),
            38 => Ok(Self::Mbx0RecovFault),
            39 => Ok(Self::Mbx1FatalFault),
            40 => Ok(Self::Mbx1RecovFault),
            41 => Ok(Self::RvCoreIbexFatalSwErr),
            42 => Ok(Self::RvCoreIbexRecovSwErr),
            43 => Ok(Self::RvCoreIbexFatalHwErr),
            44 => Ok(Self::RvCoreIbexRecovHwErr),
            45 => Ok(Self::IncomingSocSocFatalAlert0),
            46 => Ok(Self::IncomingSocSocFatalAlert1),
            47 => Ok(Self::IncomingSocSocFatalAlert2),
            48 => Ok(Self::IncomingSocSocFatalAlert3),
            _ => Err(val),
        }
    }
}

/// Alert Handler Alert Source to Peripheral Map
///
/// This array is a mapping from `AlertId` to
/// `AlertPeripheral`.
pub const ALERT_FOR_PERIPHERAL: [AlertPeripheral; 49] = [
    // PwrmgrFatalFault -> AlertPeripheral::Pwrmgr
    AlertPeripheral::Pwrmgr,
    // RstmgrFatalFault -> AlertPeripheral::Rstmgr
    AlertPeripheral::Rstmgr,
    // RstmgrFatalCnstyFault -> AlertPeripheral::Rstmgr
    AlertPeripheral::Rstmgr,
    // ClkmgrRecovFault -> AlertPeripheral::Clkmgr
    AlertPeripheral::Clkmgr,
    // ClkmgrFatalFault -> AlertPeripheral::Clkmgr
    AlertPeripheral::Clkmgr,
    // SramCtrlRetAonFatalError -> AlertPeripheral::SramCtrlRetAon
    AlertPeripheral::SramCtrlRetAon,
    // OtpCtrlFatalMacroError -> AlertPeripheral::OtpCtrl
    AlertPeripheral::OtpCtrl,
    // OtpCtrlFatalCheckError -> AlertPeripheral::OtpCtrl
    AlertPeripheral::OtpCtrl,
    // OtpCtrlFatalBusIntegError -> AlertPeripheral::OtpCtrl
    AlertPeripheral::OtpCtrl,
    // OtpCtrlFatalPrimOtpAlert -> AlertPeripheral::OtpCtrl
    AlertPeripheral::OtpCtrl,
    // OtpCtrlRecovPrimOtpAlert -> AlertPeripheral::OtpCtrl
    AlertPeripheral::OtpCtrl,
    // LcCtrlFatalProgError -> AlertPeripheral::LcCtrl
    AlertPeripheral::LcCtrl,
    // LcCtrlFatalStateError -> AlertPeripheral::LcCtrl
    AlertPeripheral::LcCtrl,
    // LcCtrlFatalBusIntegError -> AlertPeripheral::LcCtrl
    AlertPeripheral::LcCtrl,
    // RvDmFatalFault -> AlertPeripheral::RvDm
    AlertPeripheral::RvDm,
    // RvPlicFatalFault -> AlertPeripheral::RvPlic
    AlertPeripheral::RvPlic,
    // RvTimerFatalFault -> AlertPeripheral::RvTimer
    AlertPeripheral::RvTimer,
    // AesRecovCtrlUpdateErr -> AlertPeripheral::Aes
    AlertPeripheral::Aes,
    // AesFatalFault -> AlertPeripheral::Aes
    AlertPeripheral::Aes,
    // HmacFatalFault -> AlertPeripheral::Hmac
    AlertPeripheral::Hmac,
    // KmacRecovOperationErr -> AlertPeripheral::Kmac
    AlertPeripheral::Kmac,
    // KmacFatalFaultErr -> AlertPeripheral::Kmac
    AlertPeripheral::Kmac,
    // OtbnFatal -> AlertPeripheral::Otbn
    AlertPeripheral::Otbn,
    // OtbnRecov -> AlertPeripheral::Otbn
    AlertPeripheral::Otbn,
    // KeymgrDpeRecovOperationErr -> AlertPeripheral::KeymgrDpe
    AlertPeripheral::KeymgrDpe,
    // KeymgrDpeFatalFaultErr -> AlertPeripheral::KeymgrDpe
    AlertPeripheral::KeymgrDpe,
    // CsrngRecovAlert -> AlertPeripheral::Csrng
    AlertPeripheral::Csrng,
    // CsrngFatalAlert -> AlertPeripheral::Csrng
    AlertPeripheral::Csrng,
    // EntropySrcRecovAlert -> AlertPeripheral::EntropySrc
    AlertPeripheral::EntropySrc,
    // EntropySrcFatalAlert -> AlertPeripheral::EntropySrc
    AlertPeripheral::EntropySrc,
    // Edn0RecovAlert -> AlertPeripheral::Edn0
    AlertPeripheral::Edn0,
    // Edn0FatalAlert -> AlertPeripheral::Edn0
    AlertPeripheral::Edn0,
    // Edn1RecovAlert -> AlertPeripheral::Edn1
    AlertPeripheral::Edn1,
    // Edn1FatalAlert -> AlertPeripheral::Edn1
    AlertPeripheral::Edn1,
    // SramCtrlMainFatalError -> AlertPeripheral::SramCtrlMain
    AlertPeripheral::SramCtrlMain,
    // RomCtrlFatal -> AlertPeripheral::RomCtrl
    AlertPeripheral::RomCtrl,
    // DmaFatalFault -> AlertPeripheral::Dma
    AlertPeripheral::Dma,
    // Mbx0FatalFault -> AlertPeripheral::Mbx0
    AlertPeripheral::Mbx0,
    // Mbx0RecovFault -> AlertPeripheral::Mbx0
    AlertPeripheral::Mbx0,
    // Mbx1FatalFault -> AlertPeripheral::Mbx1
    AlertPeripheral::Mbx1,
    // Mbx1RecovFault -> AlertPeripheral::Mbx1
    AlertPeripheral::Mbx1,
    // RvCoreIbexFatalSwErr -> AlertPeripheral::RvCoreIbex
    AlertPeripheral::RvCoreIbex,
    // RvCoreIbexRecovSwErr -> AlertPeripheral::RvCoreIbex
    AlertPeripheral::RvCoreIbex,
    // RvCoreIbexFatalHwErr -> AlertPeripheral::RvCoreIbex
    AlertPeripheral::RvCoreIbex,
    // RvCoreIbexRecovHwErr -> AlertPeripheral::RvCoreIbex
    AlertPeripheral::RvCoreIbex,
    // IncomingSocSocFatalAlert0 -> AlertPeripheral::External
    AlertPeripheral::External,
    // IncomingSocSocFatalAlert1 -> AlertPeripheral::External
    AlertPeripheral::External,
    // IncomingSocSocFatalAlert2 -> AlertPeripheral::External
    AlertPeripheral::External,
    // IncomingSocSocFatalAlert3 -> AlertPeripheral::External
    AlertPeripheral::External,
];

/// Power Manager Wakeup Signals
#[derive(Copy, Clone, PartialEq, Eq)]
#[repr(u32)]
pub enum PowerManagerWakeUps {
    SocWkupReq = 0,
}

/// Reset Manager Software Controlled Resets
#[derive(Copy, Clone, PartialEq, Eq)]
#[repr(u32)]
pub enum ResetManagerSwResets {
    SocCpu = 0,
}

/// Power Manager Reset Request Signals
#[derive(Copy, Clone, PartialEq, Eq)]
#[repr(u32)]
pub enum PowerManagerResetRequests {
    SocRstReq = 0,
}

/// Clock Manager Software-Controlled ("Gated") Clocks.
///
/// The Software has full control over these clocks.
#[derive(Copy, Clone, PartialEq, Eq)]
pub enum GateableClocks {}

/// Clock Manager Software-Hinted Clocks.
///
/// The Software has partial control over these clocks. It can ask them to stop,
/// but the clock manager is in control of whether the clock actually is stopped.
#[derive(Copy, Clone, PartialEq, Eq)]
pub enum HintableClocks {}

/// MMIO Region
///
/// MMIO region excludes any memory that is separate from the module
/// configuration space, i.e. ROM, main SRAM and mailbox SoC window are excluded
/// but retention SRAM is included.
pub const TOP_PEPPERMINT_MMIO_BASE_ADDR: usize = 0x21100000;
pub const TOP_PEPPERMINT_MMIO_SIZE_BYTES: usize = 0x1F372000;
