// Copyright lowRISC contributors (OpenTitan project).
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0
//
// tl_main package generated by `tlgen.py` tool

package tl_main_pkg;

  localparam logic [31:0] ADDR_SPACE_RV_DM__REGS          = 32'h 40230000;
  localparam logic [31:0] ADDR_SPACE_RV_DM__MEM           = 32'h 00010000;
  localparam logic [31:0] ADDR_SPACE_ROM_CTRL__ROM        = 32'h 00040000;
  localparam logic [31:0] ADDR_SPACE_ROM_CTRL__REGS       = 32'h 40210000;
  localparam logic [31:0] ADDR_SPACE_SRAM_CTRL_MAIN__REGS = 32'h 40200000;
  localparam logic [31:0] ADDR_SPACE_SRAM_CTRL_MAIN__RAM  = 32'h 10000000;
  localparam logic [31:0] ADDR_SPACE_OTP_CTRL__CORE       = 32'h 40010000;
  localparam logic [31:0] ADDR_SPACE_OTP_MACRO__PRIM      = 32'h 40020000;
  localparam logic [31:0] ADDR_SPACE_LC_CTRL__REGS        = 32'h 40030000;
  localparam logic [31:0] ADDR_SPACE_RV_PLIC              = 32'h 48000000;
  localparam logic [31:0] ADDR_SPACE_RV_TIMER             = 32'h 40000000;
  localparam logic [31:0] ADDR_SPACE_AES                  = 32'h 40100000;
  localparam logic [31:0] ADDR_SPACE_HMAC                 = 32'h 40110000;
  localparam logic [31:0] ADDR_SPACE_KMAC                 = 32'h 40120000;
  localparam logic [31:0] ADDR_SPACE_OTBN                 = 32'h 40130000;
  localparam logic [31:0] ADDR_SPACE_KEYMGR_DPE           = 32'h 40140000;
  localparam logic [31:0] ADDR_SPACE_CSRNG                = 32'h 40150000;
  localparam logic [31:0] ADDR_SPACE_ENTROPY_SRC          = 32'h 40160000;
  localparam logic [31:0] ADDR_SPACE_EDN0                 = 32'h 40170000;
  localparam logic [31:0] ADDR_SPACE_EDN1                 = 32'h 40180000;
  localparam logic [31:0] ADDR_SPACE_RV_CORE_IBEX__CFG    = 32'h 40220000;
  localparam logic [31:0] ADDR_SPACE_DMA                  = 32'h 40300000;
  localparam logic [31:0] ADDR_SPACE_AHB_BRIDGE__CTN      = 32'h 80000000;
  localparam logic [31:0] ADDR_SPACE_MBX0__CORE           = 32'h 40310000;
  localparam logic [31:0] ADDR_SPACE_MBX1__CORE           = 32'h 40320000;
  localparam logic [31:0] ADDR_SPACE_PWRMGR               = 32'h 41000000;
  localparam logic [31:0] ADDR_SPACE_RSTMGR               = 32'h 41010000;
  localparam logic [31:0] ADDR_SPACE_CLKMGR               = 32'h 41020000;
  localparam logic [31:0] ADDR_SPACE_ALERT_HANDLER        = 32'h 41040000;
  localparam logic [31:0] ADDR_SPACE_SRAM_CTRL_RET__REGS  = 32'h 41050000;
  localparam logic [31:0] ADDR_SPACE_SRAM_CTRL_RET__RAM   = 32'h 41100000;

  localparam logic [31:0] ADDR_MASK_RV_DM__REGS          = 32'h 0000000f;
  localparam logic [31:0] ADDR_MASK_RV_DM__MEM           = 32'h 00000fff;
  localparam logic [31:0] ADDR_MASK_ROM_CTRL__ROM        = 32'h 0001ffff;
  localparam logic [31:0] ADDR_MASK_ROM_CTRL__REGS       = 32'h 0000007f;
  localparam logic [31:0] ADDR_MASK_SRAM_CTRL_MAIN__REGS = 32'h 0000003f;
  localparam logic [31:0] ADDR_SIZE_SRAM_CTRL_MAIN__RAM  = 32'h 00030000;
  localparam logic [31:0] ADDR_MASK_OTP_CTRL__CORE       = 32'h 00000fff;
  localparam logic [31:0] ADDR_MASK_OTP_MACRO__PRIM      = 32'h 0000001f;
  localparam logic [31:0] ADDR_MASK_LC_CTRL__REGS        = 32'h 000000ff;
  localparam logic [31:0] ADDR_MASK_RV_PLIC              = 32'h 07ffffff;
  localparam logic [31:0] ADDR_MASK_RV_TIMER             = 32'h 000001ff;
  localparam logic [31:0] ADDR_MASK_AES                  = 32'h 000000ff;
  localparam logic [31:0] ADDR_MASK_HMAC                 = 32'h 00001fff;
  localparam logic [31:0] ADDR_MASK_KMAC                 = 32'h 00000fff;
  localparam logic [31:0] ADDR_MASK_OTBN                 = 32'h 0000ffff;
  localparam logic [31:0] ADDR_MASK_KEYMGR_DPE           = 32'h 000000ff;
  localparam logic [31:0] ADDR_MASK_CSRNG                = 32'h 0000007f;
  localparam logic [31:0] ADDR_MASK_ENTROPY_SRC          = 32'h 000000ff;
  localparam logic [31:0] ADDR_MASK_EDN0                 = 32'h 0000007f;
  localparam logic [31:0] ADDR_MASK_EDN1                 = 32'h 0000007f;
  localparam logic [31:0] ADDR_MASK_RV_CORE_IBEX__CFG    = 32'h 000007ff;
  localparam logic [31:0] ADDR_MASK_DMA                  = 32'h 000001ff;
  localparam logic [31:0] ADDR_MASK_AHB_BRIDGE__CTN      = 32'h 7fffffff;
  localparam logic [31:0] ADDR_MASK_MBX0__CORE           = 32'h 0000007f;
  localparam logic [31:0] ADDR_MASK_MBX1__CORE           = 32'h 0000007f;
  localparam logic [31:0] ADDR_MASK_PWRMGR               = 32'h 0000007f;
  localparam logic [31:0] ADDR_MASK_RSTMGR               = 32'h 0000003f;
  localparam logic [31:0] ADDR_MASK_CLKMGR               = 32'h 0000003f;
  localparam logic [31:0] ADDR_MASK_ALERT_HANDLER        = 32'h 000007ff;
  localparam logic [31:0] ADDR_MASK_SRAM_CTRL_RET__REGS  = 32'h 0000003f;
  localparam logic [31:0] ADDR_MASK_SRAM_CTRL_RET__RAM   = 32'h 00001fff;

  localparam int N_HOST   = 6;
  localparam int N_DEVICE = 31;

  typedef enum int {
    TlRvDmRegs = 0,
    TlRvDmMem = 1,
    TlRomCtrlRom = 2,
    TlRomCtrlRegs = 3,
    TlSramCtrlMainRegs = 4,
    TlSramCtrlMainRam = 5,
    TlOtpCtrlCore = 6,
    TlOtpMacroPrim = 7,
    TlLcCtrlRegs = 8,
    TlRvPlic = 9,
    TlRvTimer = 10,
    TlAes = 11,
    TlHmac = 12,
    TlKmac = 13,
    TlOtbn = 14,
    TlKeymgrDpe = 15,
    TlCsrng = 16,
    TlEntropySrc = 17,
    TlEdn0 = 18,
    TlEdn1 = 19,
    TlRvCoreIbexCfg = 20,
    TlDma = 21,
    TlAhbBridgeCtn = 22,
    TlMbx0Core = 23,
    TlMbx1Core = 24,
    TlPwrmgr = 25,
    TlRstmgr = 26,
    TlClkmgr = 27,
    TlAlertHandler = 28,
    TlSramCtrlRetRegs = 29,
    TlSramCtrlRetRam = 30
  } tl_device_e;

  typedef enum int {
    TlRvCoreIbexCorei = 0,
    TlRvCoreIbexCored = 1,
    TlRvDmSba = 2,
    TlDmaHost = 3,
    TlMbx0Sram = 4,
    TlMbx1Sram = 5
  } tl_host_e;

endpackage
