#!/usr/bin/env python3
# Copyright lowRISC contributors (OpenTitan project).
# Licensed under the Apache License, Version 2.0, see LICENSE for details.
# SPDX-License-Identifier: Apache-2.0
"""Convert a FuseSoC .eda.yml into a slang/yosys-slang command file.

Called by gen_flist.sh; not meant to be run standalone.
"""
import os
import sys

import yaml

RTL_FILE_TYPES = {"systemVerilogSource", "verilogSource"}


def globalize(eda_dir, local_name):
    """Resolve a FuseSoC-local (work-dir-relative) name to a global path.
    """
    return os.path.realpath(os.path.join(eda_dir, local_name))


def main():
    eda_yml_path, flist_out_path = sys.argv[1], sys.argv[2]
    eda_dir = os.path.dirname(os.path.abspath(eda_yml_path))

    with open(eda_yml_path) as fh:
        eda = yaml.safe_load(fh)

    sources = []
    incdirs = []
    seen_incdirs = set()
    for f in eda["files"]:
        if f.get("file_type") not in RTL_FILE_TYPES:
            # Drops Verilator waiver (.vlt) files and "user" helper scripts,
            # which read_slang/slang cannot (and need not) parse.
            continue
        global_name = globalize(eda_dir, f["name"])
        if f.get("is_include_file"):
            # Headers (.svh) are not compiled directly; expose their
            # directory as a search path instead, mirroring how they were
            # `included.
            incdir = os.path.dirname(global_name)
            if incdir not in seen_incdirs:
                seen_incdirs.add(incdir)
                incdirs.append(incdir)
            continue
        sources.append(global_name)

    # vlogdefine parameters FuseSoC resolved for this target (e.g. SYNTHESIS=1).
    defines = []
    for name, param in (eda.get("parameters") or {}).items():
        if param.get("paramtype") != "vlogdefine":
            continue
        value = param.get("default")
        if isinstance(value, bool):
            if value:
                defines.append(f"-D{name}=1")
            # A False vlogdefine must be left undefined, not defined to
            # 0/false, since RTL typically guards on `ifdef alone.
        elif value not in (None, ""):
            defines.append(f"-D{name}={value}")
        else:
            defines.append(f"-D{name}")

    with open(flist_out_path, "w") as out:
        out.write(
            "// Auto-generated by gen_flist.sh -- do not edit by hand.\n")
        out.write(f"// FuseSoC core:   {eda['name']}\n")
        out.write(f"// Elaboration top: {eda['toplevel']}\n\n")
        for incdir in incdirs:
            out.write(f"+incdir+{incdir}\n")
        if defines:
            out.write("\n")
            for define in defines:
                out.write(f"{define}\n")
        out.write("\n")
        for source in sources:
            out.write(f"{source}\n")

    print(
        f"==> wrote {len(sources)} source files, {len(incdirs)} incdirs, "
        f"{len(defines)} defines to {flist_out_path}",
        file=sys.stderr,
    )


if __name__ == "__main__":
    main()
