// Copyright lowRISC contributors (OpenTitan project).
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0
//
// xbar_env_pkg__params generated by `tlgen.py` tool


// List of Xbar device memory map
tl_device_t xbar_devices[$] = '{
    '{"mbx0__soc", '{
        '{32'h00000000, 32'h0000001f}
    }},
    '{"mbx1__soc", '{
        '{32'h00010000, 32'h0001001f}
}}};

  // List of Xbar hosts
tl_host_t xbar_hosts[$] = '{
    '{"ahb_bridge__socmbx", 0, '{
        "mbx0__soc",
        "mbx1__soc"}}
};
