// Copyright lowRISC contributors (OpenTitan project).
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0
//
// xbar_socmbx_bind module generated by `tlgen.py` tool for assertions
module xbar_socmbx_bind;
`ifndef GATE_LEVEL
  // Host interfaces
  bind xbar_socmbx tlul_assert #(.EndpointType("Device")) tlul_assert_host_ext_socmbx_host (
    .clk_i  (clk_main_i),
    .rst_ni (rst_main_ni),
    .h2d    (tl_ext_socmbx_host_i),
    .d2h    (tl_ext_socmbx_host_o)
  );

  // Device interfaces
  bind xbar_socmbx tlul_assert #(.EndpointType("Host")) tlul_assert_device_mbx0__soc (
    .clk_i  (clk_main_i),
    .rst_ni (rst_main_ni),
    .h2d    (tl_mbx0__soc_o),
    .d2h    (tl_mbx0__soc_i)
  );
  bind xbar_socmbx tlul_assert #(.EndpointType("Host")) tlul_assert_device_mbx1__soc (
    .clk_i  (clk_main_i),
    .rst_ni (rst_main_ni),
    .h2d    (tl_mbx1__soc_o),
    .d2h    (tl_mbx1__soc_i)
  );
`endif
endmodule
