// Copyright lowRISC contributors (OpenTitan project).
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0
//
// tl_socdbg package generated by `tlgen.py` tool

package tl_socdbg_pkg;

  localparam logic [31:0] ADDR_SPACE_LC_CTRL__DMI = 32'h 00003000;
  localparam logic [31:0] ADDR_SPACE_RV_DM__DBG   = 32'h 00000000;

  localparam logic [31:0] ADDR_MASK_LC_CTRL__DMI = 32'h 00000fff;
  localparam logic [31:0] ADDR_MASK_RV_DM__DBG   = 32'h 000001ff;

  localparam int N_HOST   = 1;
  localparam int N_DEVICE = 2;

  typedef enum int {
    TlLcCtrlDmi = 0,
    TlRvDmDbg = 1
  } tl_device_e;

  typedef enum int {
    TlExtSocdbgHost = 0
  } tl_host_e;

endpackage
