// Copyright lowRISC contributors (OpenTitan project).
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0
//
// xbar_socdbg module generated by `tlgen.py` tool
// all reset signals should be generated from one reset signal to not make any deadlock
//
// Interconnect
// ext_socdbg_host
//   -> s1n_3
//     -> lc_ctrl.dmi
//     -> rv_dm.dbg

module xbar_socdbg (
  input clk_main_i,
  input rst_main_ni,

  // Host interfaces
  input  tlul_pkg::tl_h2d_t tl_ext_socdbg_host_i,
  output tlul_pkg::tl_d2h_t tl_ext_socdbg_host_o,

  // Device interfaces
  output tlul_pkg::tl_h2d_t tl_lc_ctrl__dmi_o,
  input  tlul_pkg::tl_d2h_t tl_lc_ctrl__dmi_i,
  output tlul_pkg::tl_h2d_t tl_rv_dm__dbg_o,
  input  tlul_pkg::tl_d2h_t tl_rv_dm__dbg_i,

  input prim_mubi_pkg::mubi4_t scanmode_i
);

  import tlul_pkg::*;
  import tl_socdbg_pkg::*;

  // scanmode_i is currently not used, but provisioned for future use
  // this assignment prevents lint warnings
  logic unused_scanmode;
  assign unused_scanmode = ^scanmode_i;

  tl_h2d_t tl_s1n_3_us_h2d ;
  tl_d2h_t tl_s1n_3_us_d2h ;


  tl_h2d_t tl_s1n_3_ds_h2d [2];
  tl_d2h_t tl_s1n_3_ds_d2h [2];

  // Create steering signal
  logic [1:0] dev_sel_s1n_3;



  assign tl_lc_ctrl__dmi_o = tl_s1n_3_ds_h2d[0];
  assign tl_s1n_3_ds_d2h[0] = tl_lc_ctrl__dmi_i;

  assign tl_rv_dm__dbg_o = tl_s1n_3_ds_h2d[1];
  assign tl_s1n_3_ds_d2h[1] = tl_rv_dm__dbg_i;

  assign tl_s1n_3_us_h2d = tl_ext_socdbg_host_i;
  assign tl_ext_socdbg_host_o = tl_s1n_3_us_d2h;

  always_comb begin
    // default steering to generate error response if address is not within the range
    dev_sel_s1n_3 = 2'd2;
    if ((tl_s1n_3_us_h2d.a_address &
         ~(ADDR_MASK_LC_CTRL__DMI)) == ADDR_SPACE_LC_CTRL__DMI) begin
      dev_sel_s1n_3 = 2'd0;

    end else if ((tl_s1n_3_us_h2d.a_address &
                  ~(ADDR_MASK_RV_DM__DBG)) == ADDR_SPACE_RV_DM__DBG) begin
      dev_sel_s1n_3 = 2'd1;
end
  end


  // Instantiation phase
  tlul_socket_1n #(
    .HReqDepth (4'h0),
    .HRspDepth (4'h0),
    .DReqDepth (8'h0),
    .DRspDepth (8'h0),
    .N         (2)
  ) u_s1n_3 (
    .clk_i        (clk_main_i),
    .rst_ni       (rst_main_ni),
    .tl_h_i       (tl_s1n_3_us_h2d),
    .tl_h_o       (tl_s1n_3_us_d2h),
    .tl_d_o       (tl_s1n_3_ds_h2d),
    .tl_d_i       (tl_s1n_3_ds_d2h),
    .dev_select_i (dev_sel_s1n_3)
  );

endmodule
