// Copyright lowRISC contributors (OpenTitan project).
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0
//
// tb__xbar_connect generated by `tlgen.py` tool

xbar_aon dut();

`DRIVE_CLK(clk_aon_i)

initial force dut.clk_aon_i = clk_aon_i;

// TODO, all resets tie together
initial force dut.rst_aon_ni = rst_n;

// Host TileLink interface connections
`CONNECT_TL_HOST_IF(main, dut, clk_aon_i, rst_n)

// Device TileLink interface connections
`CONNECT_TL_DEVICE_IF(pwrmgr, dut, clk_aon_i, rst_n)
`CONNECT_TL_DEVICE_IF(rstmgr, dut, clk_aon_i, rst_n)
`CONNECT_TL_DEVICE_IF(clkmgr, dut, clk_aon_i, rst_n)
`CONNECT_TL_DEVICE_IF(alert_handler, dut, clk_aon_i, rst_n)
`CONNECT_TL_DEVICE_IF(rv_timer_aon, dut, clk_aon_i, rst_n)
`CONNECT_TL_DEVICE_IF(sram_ctrl_ret_aon__regs, dut, clk_aon_i, rst_n)
`CONNECT_TL_DEVICE_IF(sram_ctrl_ret_aon__ram, dut, clk_aon_i, rst_n)
