// Copyright lowRISC contributors (OpenTitan project).
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0
//
// xbar_env_pkg__params generated by `tlgen.py` tool


// List of Xbar device memory map
tl_device_t xbar_devices[$] = '{
    '{"pwrmgr", '{
        '{32'h40400000, 32'h4040007f}
    }},
    '{"rstmgr", '{
        '{32'h40410000, 32'h4041003f}
    }},
    '{"clkmgr", '{
        '{32'h40420000, 32'h4042003f}
    }},
    '{"alert_handler", '{
        '{32'h40450000, 32'h404507ff}
    }},
    '{"sram_ctrl_ret_aon__regs", '{
        '{32'h40460000, 32'h4046003f}
    }},
    '{"sram_ctrl_ret_aon__ram", '{
        '{32'h40470000, 32'h40471fff}
}}};

  // List of Xbar hosts
tl_host_t xbar_hosts[$] = '{
    '{"main", 0, '{
        "pwrmgr",
        "rstmgr",
        "clkmgr",
        "alert_handler",
        "sram_ctrl_ret_aon__regs",
        "sram_ctrl_ret_aon__ram"}}
};
