// Copyright lowRISC contributors (OpenTitan project).
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0
//
// xbar_env_pkg__params generated by `tlgen.py` tool


// List of Xbar device memory map
tl_device_t xbar_devices[$] = '{
    '{"pwrmgr", '{
        '{32'h41000000, 32'h4100007f}
    }},
    '{"rstmgr", '{
        '{32'h41010000, 32'h4101003f}
    }},
    '{"clkmgr", '{
        '{32'h41020000, 32'h4102003f}
    }},
    '{"alert_handler", '{
        '{32'h41040000, 32'h410407ff}
    }},
    '{"rv_timer_aon", '{
        '{32'h41030000, 32'h410301ff}
    }},
    '{"sram_ctrl_ret_aon__regs", '{
        '{32'h41050000, 32'h4105003f}
    }},
    '{"sram_ctrl_ret_aon__ram", '{
        '{32'h41100000, 32'h41101fff}
}}};

  // List of Xbar hosts
tl_host_t xbar_hosts[$] = '{
    '{"main", 0, '{
        "pwrmgr",
        "rstmgr",
        "clkmgr",
        "alert_handler",
        "rv_timer_aon",
        "sram_ctrl_ret_aon__regs",
        "sram_ctrl_ret_aon__ram"}}
};
