// Copyright lowRISC contributors (OpenTitan project).
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0
//
// xbar_aon_bind module generated by `tlgen.py` tool for assertions
module xbar_aon_bind;
`ifndef GATE_LEVEL
  // Host interfaces
  bind xbar_aon tlul_assert #(.EndpointType("Device")) tlul_assert_host_main (
    .clk_i  (clk_aon_i),
    .rst_ni (rst_aon_ni),
    .h2d    (tl_main_i),
    .d2h    (tl_main_o)
  );

  // Device interfaces
  bind xbar_aon tlul_assert #(.EndpointType("Host")) tlul_assert_device_pwrmgr (
    .clk_i  (clk_aon_i),
    .rst_ni (rst_aon_ni),
    .h2d    (tl_pwrmgr_o),
    .d2h    (tl_pwrmgr_i)
  );
  bind xbar_aon tlul_assert #(.EndpointType("Host")) tlul_assert_device_rstmgr (
    .clk_i  (clk_aon_i),
    .rst_ni (rst_aon_ni),
    .h2d    (tl_rstmgr_o),
    .d2h    (tl_rstmgr_i)
  );
  bind xbar_aon tlul_assert #(.EndpointType("Host")) tlul_assert_device_clkmgr (
    .clk_i  (clk_aon_i),
    .rst_ni (rst_aon_ni),
    .h2d    (tl_clkmgr_o),
    .d2h    (tl_clkmgr_i)
  );
  bind xbar_aon tlul_assert #(.EndpointType("Host")) tlul_assert_device_alert_handler (
    .clk_i  (clk_aon_i),
    .rst_ni (rst_aon_ni),
    .h2d    (tl_alert_handler_o),
    .d2h    (tl_alert_handler_i)
  );
  bind xbar_aon tlul_assert #(.EndpointType("Host")) tlul_assert_device_sram_ctrl_ret__regs (
    .clk_i  (clk_aon_i),
    .rst_ni (rst_aon_ni),
    .h2d    (tl_sram_ctrl_ret__regs_o),
    .d2h    (tl_sram_ctrl_ret__regs_i)
  );
  bind xbar_aon tlul_assert #(.EndpointType("Host")) tlul_assert_device_sram_ctrl_ret__ram (
    .clk_i  (clk_aon_i),
    .rst_ni (rst_aon_ni),
    .h2d    (tl_sram_ctrl_ret__ram_o),
    .d2h    (tl_sram_ctrl_ret__ram_i)
  );
`endif
endmodule
