// Copyright lowRISC contributors (OpenTitan project).
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0
//
// xbar_env_pkg__params generated by `tlgen.py` tool


// List of Xbar device memory map
tl_device_t xbar_devices[$] = '{
    '{"rv_dm__regs", '{
        '{32'h40230000, 32'h4023000f}
    }},
    '{"rv_dm__mem", '{
        '{32'h00010000, 32'h00010fff}
    }},
    '{"rom_ctrl__rom", '{
        '{32'h00040000, 32'h0005ffff}
    }},
    '{"rom_ctrl__regs", '{
        '{32'h40210000, 32'h4021007f}
    }},
    '{"sram_ctrl_main__regs", '{
        '{32'h40200000, 32'h4020003f}
    }},
    '{"sram_ctrl_main__ram", '{
        '{32'h10000000, 32'h1002ffff}
    }},
    '{"otp_ctrl__core", '{
        '{32'h40010000, 32'h40013fff}
    }},
    '{"otp_macro__prim", '{
        '{32'h40020000, 32'h4002001f}
    }},
    '{"lc_ctrl__regs", '{
        '{32'h40030000, 32'h400300ff}
    }},
    '{"rv_plic", '{
        '{32'h48000000, 32'h4fffffff}
    }},
    '{"rv_timer", '{
        '{32'h40000000, 32'h400001ff}
    }},
    '{"aes", '{
        '{32'h40100000, 32'h401000ff}
    }},
    '{"hmac", '{
        '{32'h40110000, 32'h40111fff}
    }},
    '{"kmac", '{
        '{32'h40120000, 32'h40120fff}
    }},
    '{"otbn", '{
        '{32'h40130000, 32'h4013ffff}
    }},
    '{"keymgr_dpe", '{
        '{32'h40140000, 32'h401400ff}
    }},
    '{"csrng", '{
        '{32'h40150000, 32'h4015007f}
    }},
    '{"entropy_src", '{
        '{32'h40160000, 32'h401600ff}
    }},
    '{"edn0", '{
        '{32'h40170000, 32'h4017007f}
    }},
    '{"edn1", '{
        '{32'h40180000, 32'h4018007f}
    }},
    '{"rv_core_ibex__cfg", '{
        '{32'h40220000, 32'h402207ff}
    }},
    '{"dma", '{
        '{32'h40300000, 32'h403001ff}
    }},
    '{"ahb_bridge__ctn", '{
        '{32'h80000000, 32'hffffffff}
    }},
    '{"mbx0__core", '{
        '{32'h40310000, 32'h4031007f}
    }},
    '{"mbx1__core", '{
        '{32'h40320000, 32'h4032007f}
    }},
    '{"pwrmgr", '{
        '{32'h41000000, 32'h4100007f}
    }},
    '{"rstmgr", '{
        '{32'h41010000, 32'h4101003f}
    }},
    '{"clkmgr", '{
        '{32'h41020000, 32'h4102003f}
    }},
    '{"alert_handler", '{
        '{32'h41040000, 32'h410407ff}
    }},
    '{"sram_ctrl_ret__regs", '{
        '{32'h41050000, 32'h4105003f}
    }},
    '{"sram_ctrl_ret__ram", '{
        '{32'h41100000, 32'h41101fff}
}}};

  // List of Xbar hosts
tl_host_t xbar_hosts[$] = '{
    '{"rv_core_ibex__corei", 0, '{
        "rv_dm__mem",
        "rom_ctrl__rom",
        "rom_ctrl__regs",
        "sram_ctrl_main__ram"}}
    ,
    '{"rv_core_ibex__cored", 1, '{
        "rv_dm__regs",
        "rv_dm__mem",
        "rom_ctrl__rom",
        "rom_ctrl__regs",
        "sram_ctrl_main__regs",
        "sram_ctrl_main__ram",
        "otp_ctrl__core",
        "otp_macro__prim",
        "lc_ctrl__regs",
        "rv_plic",
        "rv_timer",
        "aes",
        "hmac",
        "kmac",
        "otbn",
        "keymgr_dpe",
        "csrng",
        "entropy_src",
        "edn0",
        "edn1",
        "rv_core_ibex__cfg",
        "dma",
        "ahb_bridge__ctn",
        "mbx0__core",
        "mbx1__core",
        "pwrmgr",
        "rstmgr",
        "clkmgr",
        "alert_handler",
        "sram_ctrl_ret__regs",
        "sram_ctrl_ret__ram"}}
    ,
    '{"rv_dm__sba", 2, '{
        "rv_dm__regs",
        "rom_ctrl__rom",
        "rom_ctrl__regs",
        "sram_ctrl_main__regs",
        "sram_ctrl_main__ram",
        "otp_ctrl__core",
        "otp_macro__prim",
        "lc_ctrl__regs",
        "rv_plic",
        "rv_timer",
        "aes",
        "hmac",
        "kmac",
        "otbn",
        "keymgr_dpe",
        "csrng",
        "entropy_src",
        "edn0",
        "edn1",
        "rv_core_ibex__cfg",
        "dma",
        "mbx0__core",
        "mbx1__core",
        "pwrmgr",
        "rstmgr",
        "clkmgr",
        "alert_handler",
        "sram_ctrl_ret__regs",
        "sram_ctrl_ret__ram"}}
    ,
    '{"dma__host", 3, '{
        "sram_ctrl_main__ram",
        "rom_ctrl__rom",
        "ahb_bridge__ctn"}}
    ,
    '{"mbx0__sram", 4, '{
        "sram_ctrl_main__ram"}}
    ,
    '{"mbx1__sram", 5, '{
        "sram_ctrl_main__ram"}}
};
