// Copyright lowRISC contributors (OpenTitan project).
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0
//
// tl_socmbx package generated by `tlgen.py` tool

package tl_socmbx_pkg;

  localparam logic [31:0] ADDR_SPACE_MBX0__SOC = 32'h 00000000;
  localparam logic [31:0] ADDR_SPACE_MBX1__SOC = 32'h 00000100;

  localparam logic [31:0] ADDR_MASK_MBX0__SOC = 32'h 0000001f;
  localparam logic [31:0] ADDR_MASK_MBX1__SOC = 32'h 0000001f;

  localparam int N_HOST   = 1;
  localparam int N_DEVICE = 2;

  typedef enum int {
    TlMbx0Soc = 0,
    TlMbx1Soc = 1
  } tl_device_e;

  typedef enum int {
    TlAhbBridgeSocmbx = 0
  } tl_host_e;

endpackage
