// Copyright lowRISC contributors (OpenTitan project).
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0
//
// xbar_socdbg_bind module generated by `tlgen.py` tool for assertions
module xbar_socdbg_bind;
`ifndef GATE_LEVEL
  // Host interfaces
  bind xbar_socdbg tlul_assert #(.EndpointType("Device")) tlul_assert_host_ext_socdbg_host (
    .clk_i  (clk_main_i),
    .rst_ni (rst_main_ni),
    .h2d    (tl_ext_socdbg_host_i),
    .d2h    (tl_ext_socdbg_host_o)
  );

  // Device interfaces
  bind xbar_socdbg tlul_assert #(.EndpointType("Host")) tlul_assert_device_lc_ctrl__dmi (
    .clk_i  (clk_main_i),
    .rst_ni (rst_main_ni),
    .h2d    (tl_lc_ctrl__dmi_o),
    .d2h    (tl_lc_ctrl__dmi_i)
  );
  bind xbar_socdbg tlul_assert #(.EndpointType("Host")) tlul_assert_device_rv_dm__dbg (
    .clk_i  (clk_main_i),
    .rst_ni (rst_main_ni),
    .h2d    (tl_rv_dm__dbg_o),
    .d2h    (tl_rv_dm__dbg_i)
  );
`endif
endmodule
