// Copyright lowRISC contributors (OpenTitan project).
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0
//
// xbar_env_pkg__params generated by `tlgen.py` tool


// List of Xbar device memory map
tl_device_t xbar_devices[$] = '{
    '{"lc_ctrl__dmi", '{
        '{32'h00003000, 32'h00003fff}
    }},
    '{"rv_dm__dbg", '{
        '{32'h00000000, 32'h000001ff}
}}};

  // List of Xbar hosts
tl_host_t xbar_hosts[$] = '{
    '{"ext_socdbg_host", 0, '{
        "lc_ctrl__dmi",
        "rv_dm__dbg"}}
};
