// Copyright lowRISC contributors (OpenTitan project).
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0
//
// tl_aon package generated by `tlgen.py` tool

package tl_aon_pkg;

  localparam logic [31:0] ADDR_SPACE_PWRMGR                  = 32'h 41000000;
  localparam logic [31:0] ADDR_SPACE_RSTMGR                  = 32'h 41010000;
  localparam logic [31:0] ADDR_SPACE_CLKMGR                  = 32'h 41020000;
  localparam logic [31:0] ADDR_SPACE_ALERT_HANDLER           = 32'h 41040000;
  localparam logic [31:0] ADDR_SPACE_RV_TIMER_AON            = 32'h 41030000;
  localparam logic [31:0] ADDR_SPACE_SRAM_CTRL_RET_AON__REGS = 32'h 41050000;
  localparam logic [31:0] ADDR_SPACE_SRAM_CTRL_RET_AON__RAM  = 32'h 41100000;

  localparam logic [31:0] ADDR_MASK_PWRMGR                  = 32'h 0000007f;
  localparam logic [31:0] ADDR_MASK_RSTMGR                  = 32'h 0000003f;
  localparam logic [31:0] ADDR_MASK_CLKMGR                  = 32'h 0000003f;
  localparam logic [31:0] ADDR_MASK_ALERT_HANDLER           = 32'h 000007ff;
  localparam logic [31:0] ADDR_MASK_RV_TIMER_AON            = 32'h 000001ff;
  localparam logic [31:0] ADDR_MASK_SRAM_CTRL_RET_AON__REGS = 32'h 0000003f;
  localparam logic [31:0] ADDR_MASK_SRAM_CTRL_RET_AON__RAM  = 32'h 00001fff;

  localparam int N_HOST   = 1;
  localparam int N_DEVICE = 7;

  typedef enum int {
    TlPwrmgr = 0,
    TlRstmgr = 1,
    TlClkmgr = 2,
    TlAlertHandler = 3,
    TlRvTimerAon = 4,
    TlSramCtrlRetAonRegs = 5,
    TlSramCtrlRetAonRam = 6
  } tl_device_e;

  typedef enum int {
    TlMain = 0
  } tl_host_e;

endpackage
