// Copyright lowRISC contributors (OpenTitan project).
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0
//
// tb__xbar_connect generated by `topgen.py` tool

// This file must be `included in `hw/top_<toplevel>/dv/tb/tb.sv.

`define DRIVE_CHIP_TL_HOST_IF(tl_name, inst_name, sig_name, power_domain) \
     force ``tl_name``_tl_if.d2h = dut.top_peppermint.peppermint_pd_``power_domain``.u_``inst_name``.``sig_name``_i; \
     force dut.top_peppermint.peppermint_pd_``power_domain``.u_``inst_name``.``sig_name``_o = ``tl_name``_tl_if.h2d; \
     force dut.top_peppermint.peppermint_pd_``power_domain``.u_``inst_name``.clk_i = 0; \
     uvm_config_db#(virtual tl_if)::set(null, $sformatf("*env.%0s_agent", `"tl_name`"), "vif", \
                                        ``tl_name``_tl_if);

`define DRIVE_CHIP_TL_DEVICE_IF(tl_name, inst_name, sig_name, power_domain) \
     force ``tl_name``_tl_if.h2d = dut.top_peppermint.peppermint_pd_``power_domain``.u_``inst_name``.``sig_name``_i; \
     force dut.top_peppermint.peppermint_pd_``power_domain``.u_``inst_name``.``sig_name``_o = ``tl_name``_tl_if.d2h; \
     force dut.top_peppermint.peppermint_pd_``power_domain``.u_``inst_name``.clk_i = 0; \
     uvm_config_db#(virtual tl_if)::set(null, $sformatf("*env.%0s_agent", `"tl_name`"), "vif", \
                                        ``tl_name``_tl_if);

`define DRIVE_CHIP_TL_EXT_DEVICE_IF(tl_name, inst_name, port_name) \
     force ``tl_name``_tl_if.h2d = dut.u_``inst_name``.``port_name``_i; \
     force dut.u_``inst_name``.``port_name``_o = ``tl_name``_tl_if.d2h; \
     uvm_config_db#(virtual tl_if)::set(null, $sformatf("*env.%0s_agent", `"tl_name`"), "vif", \
                                        ``tl_name``_tl_if);

wire clk_main;
clk_rst_if clk_rst_if_main(.clk(clk_main), .rst_n(rst_n));
wire clk_aon;
clk_rst_if clk_rst_if_aon(.clk(clk_aon), .rst_n(rst_n));

tl_if rv_core_ibex__corei_tl_if(clk_main, rst_n);
tl_if rv_core_ibex__cored_tl_if(clk_main, rst_n);
tl_if rv_dm__sba_tl_if(clk_main, rst_n);
tl_if dma__host_tl_if(clk_main, rst_n);
tl_if mbx0__sram_tl_if(clk_main, rst_n);
tl_if mbx1__sram_tl_if(clk_main, rst_n);
tl_if ahb_bridge__socmbx_tl_if(clk_main, rst_n);
tl_if ext_socdbg_host_tl_if(clk_main, rst_n);

tl_if rv_dm__regs_tl_if(clk_main, rst_n);
tl_if rv_dm__mem_tl_if(clk_main, rst_n);
tl_if rom_ctrl__rom_tl_if(clk_main, rst_n);
tl_if rom_ctrl__regs_tl_if(clk_main, rst_n);
tl_if sram_ctrl_main__regs_tl_if(clk_main, rst_n);
tl_if sram_ctrl_main__ram_tl_if(clk_main, rst_n);
tl_if otp_ctrl__core_tl_if(clk_main, rst_n);
tl_if otp_macro__prim_tl_if(clk_main, rst_n);
tl_if lc_ctrl__regs_tl_if(clk_main, rst_n);
tl_if rv_plic_tl_if(clk_main, rst_n);
tl_if rv_timer_tl_if(clk_main, rst_n);
tl_if aes_tl_if(clk_main, rst_n);
tl_if hmac_tl_if(clk_main, rst_n);
tl_if kmac_tl_if(clk_main, rst_n);
tl_if otbn_tl_if(clk_main, rst_n);
tl_if keymgr_dpe_tl_if(clk_main, rst_n);
tl_if csrng_tl_if(clk_main, rst_n);
tl_if entropy_src_tl_if(clk_main, rst_n);
tl_if edn0_tl_if(clk_main, rst_n);
tl_if edn1_tl_if(clk_main, rst_n);
tl_if rv_core_ibex__cfg_tl_if(clk_main, rst_n);
tl_if dma_tl_if(clk_main, rst_n);
tl_if ahb_bridge__ctn_tl_if(clk_main, rst_n);
tl_if mbx0__core_tl_if(clk_main, rst_n);
tl_if mbx1__core_tl_if(clk_main, rst_n);
tl_if pwrmgr_tl_if(clk_aon, rst_n);
tl_if rstmgr_tl_if(clk_aon, rst_n);
tl_if clkmgr_tl_if(clk_aon, rst_n);
tl_if alert_handler_tl_if(clk_aon, rst_n);
tl_if sram_ctrl_ret_aon__regs_tl_if(clk_aon, rst_n);
tl_if sram_ctrl_ret_aon__ram_tl_if(clk_aon, rst_n);
tl_if mbx0__soc_tl_if(clk_main, rst_n);
tl_if mbx1__soc_tl_if(clk_main, rst_n);
tl_if lc_ctrl__dmi_tl_if(clk_main, rst_n);
tl_if rv_dm__dbg_tl_if(clk_main, rst_n);

initial begin
  wait (xbar_mode !== 1'bx);
  if (xbar_mode) begin
    // only enable assertions in xbar as many pins are unconnected
    $assertoff(0, tb);
    $asserton(0, tb.dut.top_peppermint.peppermint_pd_main.u_xbar_main);
    $asserton(0, tb.dut.top_peppermint.peppermint_pd_aon.u_xbar_aon);
    $asserton(0, tb.dut.top_peppermint.peppermint_pd_main.u_xbar_socmbx);
    $asserton(0, tb.dut.top_peppermint.peppermint_pd_main.u_xbar_socdbg);


    // These are all zero-time: anything that consumes time go at the end.

    // bypass clkmgr, force clocks directly
    force tb.dut.top_peppermint.peppermint_pd_main.u_xbar_main.clk_main_i = clk_main;
    force tb.dut.top_peppermint.peppermint_pd_main.u_xbar_main.clk_aon_i = clk_aon;
    force tb.dut.top_peppermint.peppermint_pd_aon.u_xbar_aon.clk_aon_i = clk_aon;
    force tb.dut.top_peppermint.peppermint_pd_main.u_xbar_socmbx.clk_main_i = clk_main;
    force tb.dut.top_peppermint.peppermint_pd_main.u_xbar_socdbg.clk_main_i = clk_main;

    // bypass rstmgr, force resets directly
    force tb.dut.top_peppermint.peppermint_pd_main.u_xbar_main.rst_main_ni = rst_n;
    force tb.dut.top_peppermint.peppermint_pd_main.u_xbar_main.rst_aon_ni = rst_n;
    force tb.dut.top_peppermint.peppermint_pd_aon.u_xbar_aon.rst_aon_ni = rst_n;
    force tb.dut.top_peppermint.peppermint_pd_main.u_xbar_socmbx.rst_main_ni = rst_n;
    force tb.dut.top_peppermint.peppermint_pd_main.u_xbar_socdbg.rst_main_ni = rst_n;

`ifndef GATE_LEVEL
    `DRIVE_CHIP_TL_HOST_IF(rv_core_ibex__corei, rv_core_ibex, corei_tl_h, main)
    `DRIVE_CHIP_TL_HOST_IF(rv_core_ibex__cored, rv_core_ibex, cored_tl_h, main)
    `DRIVE_CHIP_TL_HOST_IF(rv_dm__sba, rv_dm, sba_tl_h, main)
    `DRIVE_CHIP_TL_HOST_IF(dma__host, dma, host_tl_h, main)
    `DRIVE_CHIP_TL_HOST_IF(mbx0__sram, mbx0, sram_tl_h, main)
    `DRIVE_CHIP_TL_HOST_IF(mbx1__sram, mbx1, sram_tl_h, main)
    `DRIVE_CHIP_TL_DEVICE_IF(rv_dm__regs, rv_dm, regs_tl_d, main)
    `DRIVE_CHIP_TL_DEVICE_IF(rv_dm__mem, rv_dm, mem_tl_d, main)
    `DRIVE_CHIP_TL_DEVICE_IF(rom_ctrl__rom, rom_ctrl, rom_tl, main)
    `DRIVE_CHIP_TL_DEVICE_IF(rom_ctrl__regs, rom_ctrl, regs_tl, main)
    `DRIVE_CHIP_TL_DEVICE_IF(sram_ctrl_main__regs, sram_ctrl_main, regs_tl, main)
    `DRIVE_CHIP_TL_DEVICE_IF(sram_ctrl_main__ram, sram_ctrl_main, ram_tl, main)
    `DRIVE_CHIP_TL_DEVICE_IF(otp_ctrl__core, otp_ctrl, core_tl, main)
    `DRIVE_CHIP_TL_DEVICE_IF(otp_macro__prim, otp_macro, prim_tl, main)
    `DRIVE_CHIP_TL_DEVICE_IF(lc_ctrl__regs, lc_ctrl, regs_tl, main)
    `DRIVE_CHIP_TL_DEVICE_IF(rv_plic, rv_plic, tl, main)
    `DRIVE_CHIP_TL_DEVICE_IF(rv_timer, rv_timer, tl, main)
    `DRIVE_CHIP_TL_DEVICE_IF(aes, aes, tl, main)
    `DRIVE_CHIP_TL_DEVICE_IF(hmac, hmac, tl, main)
    `DRIVE_CHIP_TL_DEVICE_IF(kmac, kmac, tl, main)
    `DRIVE_CHIP_TL_DEVICE_IF(otbn, otbn, tl, main)
    `DRIVE_CHIP_TL_DEVICE_IF(keymgr_dpe, keymgr_dpe, tl, main)
    `DRIVE_CHIP_TL_DEVICE_IF(csrng, csrng, tl, main)
    `DRIVE_CHIP_TL_DEVICE_IF(entropy_src, entropy_src, tl, main)
    `DRIVE_CHIP_TL_DEVICE_IF(edn0, edn0, tl, main)
    `DRIVE_CHIP_TL_DEVICE_IF(edn1, edn1, tl, main)
    `DRIVE_CHIP_TL_DEVICE_IF(rv_core_ibex__cfg, rv_core_ibex, cfg_tl_d, main)
    `DRIVE_CHIP_TL_DEVICE_IF(dma, dma, host_tl_h, main)
    `DRIVE_CHIP_TL_DEVICE_IF(ahb_bridge__ctn, ahb_bridge, ctn_tl_d, main)
    `DRIVE_CHIP_TL_DEVICE_IF(mbx0__core, mbx0, core_tl_d, main)
    `DRIVE_CHIP_TL_DEVICE_IF(mbx1__core, mbx1, core_tl_d, main)
    `DRIVE_CHIP_TL_DEVICE_IF(pwrmgr, pwrmgr, tl, aon)
    `DRIVE_CHIP_TL_DEVICE_IF(rstmgr, rstmgr, tl, aon)
    `DRIVE_CHIP_TL_DEVICE_IF(clkmgr, clkmgr, tl, aon)
    `DRIVE_CHIP_TL_DEVICE_IF(alert_handler, alert_handler, tl, aon)
    `DRIVE_CHIP_TL_DEVICE_IF(sram_ctrl_ret_aon__regs, sram_ctrl_ret_aon, regs_tl, aon)
    `DRIVE_CHIP_TL_DEVICE_IF(sram_ctrl_ret_aon__ram, sram_ctrl_ret_aon, ram_tl, aon)
    `DRIVE_CHIP_TL_HOST_IF(ahb_bridge__socmbx, ahb_bridge, socmbx_tl_h, main)
    `DRIVE_CHIP_TL_DEVICE_IF(mbx0__soc, mbx0, soc_tl_d, main)
    `DRIVE_CHIP_TL_DEVICE_IF(mbx1__soc, mbx1, soc_tl_d, main)
    // ext_socdbg_host: no on-chip far end found; skipping DV force connection.
    `DRIVE_CHIP_TL_DEVICE_IF(lc_ctrl__dmi, lc_ctrl, dmi_tl, main)
    `DRIVE_CHIP_TL_DEVICE_IF(rv_dm__dbg, rv_dm, dbg_tl_d, main)
`endif

    // And this can consume time, so they go at the end of this block.

    // Wait for a negedge of rst_n, or else we will have clock edges before
    // reset, which could capture 'X values.
    xbar_clk_rst_if.wait_for_reset(.wait_posedge(1'b0));

    clk_rst_if_main.set_active(.drive_rst_n_val(0));
    clk_rst_if_main.set_freq_khz(400000000 / 1000);
    clk_rst_if_aon.set_active(.drive_rst_n_val(0));
    clk_rst_if_aon.set_freq_khz(32768 / 1000);

  end
end

`undef DRIVE_CHIP_TL_HOST_IF
`undef DRIVE_CHIP_TL_DEVICE_IF
`undef DRIVE_CHIP_TL_EXT_DEVICE_IF
