// Copyright lowRISC contributors (OpenTitan project).
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0
//
// xbar_env_pkg__params generated by `topgen.py` tool


// List of Xbar device memory map
tl_device_t xbar_devices[$] = '{
    '{"rv_dm__regs", '{
        '{32'h21200000, 32'h2120000f}
    }},
    '{"rv_dm__mem", '{
        '{32'h00050000, 32'h00050fff}
    }},
    '{"rom_ctrl__rom", '{
        '{32'h00020000, 32'h0004ffff}
    }},
    '{"rom_ctrl__regs", '{
        '{32'h211e0000, 32'h211e007f}
    }},
    '{"sram_ctrl_main__regs", '{
        '{32'h211c0000, 32'h211c003f}
    }},
    '{"sram_ctrl_main__ram", '{
        '{32'h10000000, 32'h1002ffff}
    }},
    '{"otp_ctrl__core", '{
        '{32'h30130000, 32'h30133fff}
    }},
    '{"otp_macro__prim", '{
        '{32'h30140000, 32'h3014001f}
    }},
    '{"lc_ctrl__regs", '{
        '{32'h30150000, 32'h301500ff}
    }},
    '{"rv_plic", '{
        '{32'h28000000, 32'h2fffffff}
    }},
    '{"rv_timer", '{
        '{32'h21190000, 32'h211901ff}
    }},
    '{"aes", '{
        '{32'h21100000, 32'h211000ff}
    }},
    '{"hmac", '{
        '{32'h21110000, 32'h21111fff}
    }},
    '{"kmac", '{
        '{32'h21120000, 32'h21120fff}
    }},
    '{"otbn", '{
        '{32'h21130000, 32'h2113ffff}
    }},
    '{"keymgr_dpe", '{
        '{32'h21140000, 32'h211400ff}
    }},
    '{"csrng", '{
        '{32'h21150000, 32'h2115007f}
    }},
    '{"entropy_src", '{
        '{32'h21160000, 32'h211600ff}
    }},
    '{"edn0", '{
        '{32'h21170000, 32'h2117007f}
    }},
    '{"edn1", '{
        '{32'h21180000, 32'h2118007f}
    }},
    '{"rv_core_ibex__cfg", '{
        '{32'h211f0000, 32'h211f07ff}
    }},
    '{"dma", '{
        '{32'h22010000, 32'h220101ff}
    }},
    '{"ahb_bridge__ctn", '{
        '{32'h80000000, 32'h8fffffff}
    }},
    '{"mbx0__core", '{
        '{32'h22000000, 32'h2200007f}
    }},
    '{"mbx1__core", '{
        '{32'h22000100, 32'h2200017f}
    }},
    '{"pwrmgr", '{
        '{32'h40400000, 32'h4040007f}
    }},
    '{"rstmgr", '{
        '{32'h40410000, 32'h4041003f}
    }},
    '{"clkmgr", '{
        '{32'h40420000, 32'h4042003f}
    }},
    '{"alert_handler", '{
        '{32'h40450000, 32'h404507ff}
    }},
    '{"rv_timer_aon", '{
        '{32'h40430000, 32'h404301ff}
    }},
    '{"sram_ctrl_ret_aon__regs", '{
        '{32'h40460000, 32'h4046003f}
    }},
    '{"sram_ctrl_ret_aon__ram", '{
        '{32'h40470000, 32'h40471fff}
    }},
    '{"mbx0__soc", '{
        '{32'h00000000, 32'h0000001f}
    }},
    '{"mbx1__soc", '{
        '{32'h00000100, 32'h0000011f}
    }},
    '{"lc_ctrl__dmi", '{
        '{32'h00003000, 32'h00003fff}
    }},
    '{"rv_dm__dbg", '{
        '{32'h00000000, 32'h000001ff}
    }}};

  // List of Xbar hosts
tl_host_t xbar_hosts[$] = '{
    '{"rv_core_ibex__corei", 0, '{
        "rv_dm__mem",
        "rom_ctrl__rom",
        "rom_ctrl__regs",
        "sram_ctrl_main__ram"}}
    ,
    '{"rv_core_ibex__cored", 1, '{
        "rv_dm__regs",
        "rv_dm__mem",
        "rom_ctrl__rom",
        "rom_ctrl__regs",
        "sram_ctrl_main__regs",
        "sram_ctrl_main__ram",
        "otp_ctrl__core",
        "otp_macro__prim",
        "lc_ctrl__regs",
        "rv_plic",
        "rv_timer",
        "aes",
        "hmac",
        "kmac",
        "otbn",
        "keymgr_dpe",
        "csrng",
        "entropy_src",
        "edn0",
        "edn1",
        "rv_core_ibex__cfg",
        "dma",
        "ahb_bridge__ctn",
        "mbx0__core",
        "mbx1__core",
        "pwrmgr",
        "rstmgr",
        "clkmgr",
        "alert_handler",
        "rv_timer_aon",
        "sram_ctrl_ret_aon__regs",
        "sram_ctrl_ret_aon__ram"}}
    ,
    '{"rv_dm__sba", 2, '{
        "rv_dm__regs",
        "rom_ctrl__rom",
        "rom_ctrl__regs",
        "sram_ctrl_main__regs",
        "sram_ctrl_main__ram",
        "otp_ctrl__core",
        "otp_macro__prim",
        "lc_ctrl__regs",
        "rv_plic",
        "rv_timer",
        "aes",
        "hmac",
        "kmac",
        "otbn",
        "keymgr_dpe",
        "csrng",
        "entropy_src",
        "edn0",
        "edn1",
        "rv_core_ibex__cfg",
        "dma",
        "mbx0__core",
        "mbx1__core",
        "pwrmgr",
        "rstmgr",
        "clkmgr",
        "alert_handler",
        "rv_timer_aon",
        "sram_ctrl_ret_aon__regs",
        "sram_ctrl_ret_aon__ram"}}
    ,
    '{"dma__host", 3, '{
        "sram_ctrl_main__ram",
        "rom_ctrl__rom",
        "ahb_bridge__ctn"}}
    ,
    '{"mbx0__sram", 4, '{
        "sram_ctrl_main__ram"}}
    ,
    '{"mbx1__sram", 5, '{
        "sram_ctrl_main__ram"}}
};
