// Copyright lowRISC contributors (OpenTitan project).
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0
//
// Register Package auto-generated by `reggen` containing data structure

package clkmgr_reg_pkg;

  // Param list
  parameter int NumGroups = 2;
  parameter int NumSwGateableClocks = 0;
  parameter int NumHintableClocks = 0;
  parameter int NumAlerts = 2;

  // Address widths within the block
  parameter int BlockAw = 6;

  // Number of registers for every interface
  parameter int NumRegs = 8;

  // Alert indices
  typedef enum int {
    AlertRecovFaultIdx = 0,
    AlertFatalFaultIdx = 1
  } clkmgr_alert_idx_t;

  ////////////////////////////
  // Typedefs for registers //
  ////////////////////////////

  typedef struct packed {
    struct packed {
      logic        q;
      logic        qe;
    } fatal_fault;
    struct packed {
      logic        q;
      logic        qe;
    } recov_fault;
  } clkmgr_reg2hw_alert_test_reg_t;

  typedef struct packed {
    logic [3:0]  q;
  } clkmgr_reg2hw_jitter_enable_reg_t;

  typedef struct packed {
    logic        q;
  } clkmgr_reg2hw_measure_ctrl_regwen_reg_t;

  typedef struct packed {
    logic [3:0]  q;
  } clkmgr_reg2hw_main_meas_ctrl_en_reg_t;

  typedef struct packed {
    struct packed {
      logic [14:0] q;
    } lo;
    struct packed {
      logic [14:0] q;
    } hi;
  } clkmgr_reg2hw_main_meas_ctrl_shadowed_reg_t;

  typedef struct packed {
    struct packed {
      logic        q;
    } shadow_storage_err;
    struct packed {
      logic        q;
    } idle_cnt;
    struct packed {
      logic        q;
    } reg_intg;
  } clkmgr_reg2hw_fatal_err_code_reg_t;

  typedef struct packed {
    logic        d;
    logic        de;
  } clkmgr_hw2reg_measure_ctrl_regwen_reg_t;

  typedef struct packed {
    logic [3:0]  d;
    logic        de;
  } clkmgr_hw2reg_main_meas_ctrl_en_reg_t;

  typedef struct packed {
    struct packed {
      logic        d;
      logic        de;
    } main_timeout_err;
    struct packed {
      logic        d;
      logic        de;
    } main_measure_err;
    struct packed {
      logic        d;
      logic        de;
    } shadow_update_err;
  } clkmgr_hw2reg_recov_err_code_reg_t;

  typedef struct packed {
    struct packed {
      logic        d;
      logic        de;
    } shadow_storage_err;
    struct packed {
      logic        d;
      logic        de;
    } idle_cnt;
    struct packed {
      logic        d;
      logic        de;
    } reg_intg;
  } clkmgr_hw2reg_fatal_err_code_reg_t;

  // Register -> HW type
  typedef struct packed {
    clkmgr_reg2hw_alert_test_reg_t alert_test; // [45:42]
    clkmgr_reg2hw_jitter_enable_reg_t jitter_enable; // [41:38]
    clkmgr_reg2hw_measure_ctrl_regwen_reg_t measure_ctrl_regwen; // [37:37]
    clkmgr_reg2hw_main_meas_ctrl_en_reg_t main_meas_ctrl_en; // [36:33]
    clkmgr_reg2hw_main_meas_ctrl_shadowed_reg_t main_meas_ctrl_shadowed; // [32:3]
    clkmgr_reg2hw_fatal_err_code_reg_t fatal_err_code; // [2:0]
  } clkmgr_reg2hw_t;

  // HW -> register type
  typedef struct packed {
    clkmgr_hw2reg_measure_ctrl_regwen_reg_t measure_ctrl_regwen; // [18:17]
    clkmgr_hw2reg_main_meas_ctrl_en_reg_t main_meas_ctrl_en; // [16:12]
    clkmgr_hw2reg_recov_err_code_reg_t recov_err_code; // [11:6]
    clkmgr_hw2reg_fatal_err_code_reg_t fatal_err_code; // [5:0]
  } clkmgr_hw2reg_t;

  // Register offsets
  parameter logic [BlockAw-1:0] CLKMGR_ALERT_TEST_OFFSET = 6'h 0;
  parameter logic [BlockAw-1:0] CLKMGR_JITTER_REGWEN_OFFSET = 6'h 10;
  parameter logic [BlockAw-1:0] CLKMGR_JITTER_ENABLE_OFFSET = 6'h 14;
  parameter logic [BlockAw-1:0] CLKMGR_MEASURE_CTRL_REGWEN_OFFSET = 6'h 18;
  parameter logic [BlockAw-1:0] CLKMGR_MAIN_MEAS_CTRL_EN_OFFSET = 6'h 1c;
  parameter logic [BlockAw-1:0] CLKMGR_MAIN_MEAS_CTRL_SHADOWED_OFFSET = 6'h 20;
  parameter logic [BlockAw-1:0] CLKMGR_RECOV_ERR_CODE_OFFSET = 6'h 24;
  parameter logic [BlockAw-1:0] CLKMGR_FATAL_ERR_CODE_OFFSET = 6'h 28;

  // Reset values for hwext registers and their fields
  parameter logic [1:0] CLKMGR_ALERT_TEST_RESVAL = 2'h 0;
  parameter logic [0:0] CLKMGR_ALERT_TEST_RECOV_FAULT_RESVAL = 1'h 0;
  parameter logic [0:0] CLKMGR_ALERT_TEST_FATAL_FAULT_RESVAL = 1'h 0;

  // Register index
  typedef enum int {
    CLKMGR_ALERT_TEST,
    CLKMGR_JITTER_REGWEN,
    CLKMGR_JITTER_ENABLE,
    CLKMGR_MEASURE_CTRL_REGWEN,
    CLKMGR_MAIN_MEAS_CTRL_EN,
    CLKMGR_MAIN_MEAS_CTRL_SHADOWED,
    CLKMGR_RECOV_ERR_CODE,
    CLKMGR_FATAL_ERR_CODE
  } clkmgr_id_e;

  // Register width information to check illegal writes
  parameter logic [3:0] CLKMGR_PERMIT [8] = '{
    4'b 0001, // index[0] CLKMGR_ALERT_TEST
    4'b 0001, // index[1] CLKMGR_JITTER_REGWEN
    4'b 0001, // index[2] CLKMGR_JITTER_ENABLE
    4'b 0001, // index[3] CLKMGR_MEASURE_CTRL_REGWEN
    4'b 0001, // index[4] CLKMGR_MAIN_MEAS_CTRL_EN
    4'b 1111, // index[5] CLKMGR_MAIN_MEAS_CTRL_SHADOWED
    4'b 0001, // index[6] CLKMGR_RECOV_ERR_CODE
    4'b 0001  // index[7] CLKMGR_FATAL_ERR_CODE
  };

endpackage
